/* -*- C++ -*- */
/* Generated by /workspaces/testdds/lib/OpenDDS/OpenDDS/bin/opendds_idl version 3.34.0-dev (ACE version 6.5.23) running on input file CorbaSeq/CharSeq.idl */
#ifndef OPENDDS_IDL_GENERATED_CHARSEQTYPESUPPORTIMPL_H_QBLN9L
#define OPENDDS_IDL_GENERATED_CHARSEQTYPESUPPORTIMPL_H_QBLN9L

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 34, 0)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "tao/CharSeqC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"
#include "dds/DCPS/dcps_export.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: CharSeq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct CORBA_CharSeq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<CORBA_CharSeq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<CORBA_CharSeq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::CORBA::CharSeq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::CORBA::CharSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::CORBA::CharSeq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::CORBA::CharSeq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::CORBA::CharSeq,  ::CORBA::CharSeq>(DDS::DynamicType_ptr type, const  ::CORBA::CharSeq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::CORBA::CharSeq,  ::CORBA::CharSeq>(DDS::DynamicType_ptr type,  ::CORBA::CharSeq& value);

template <>
OpenDDS_Dcps_Export const  ::CORBA::CharSeq* get_dynamic_data_adapter_value< ::CORBA::CharSeq,  ::CORBA::CharSeq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: CharSeq */

/* End MODULE: CORBA */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_CHARSEQTYPESUPPORTIMPL_H_QBLN9L */
