// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:454

#ifndef _TAO_IDL_INFOS_PGPX60_H_
#define _TAO_IDL_INFOS_PGPX60_H_

#include /**/ "ace/pre.h"

#include "InfoC.h"
#include "dds/DdsDcpsInfoUtilsS.h"
#include "dds/DdsDcpsPublicationS.h"
#include "dds/DdsDcpsSubscriptionS.h"
#include "DataWriterRemoteS.h"
#include "DataReaderRemoteS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:142

  

#if !defined (_OPENDDS_DCPS_DCPSINFO__SARG_TRAITS_)
#define _OPENDDS_DCPS_DCPSINFO__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::OpenDDS::DCPS::DCPSInfo>
    : public
        Object_SArg_Traits_T<
            ::OpenDDS::DCPS::DCPSInfo_ptr,
            ::OpenDDS::DCPS::DCPSInfo_var,
            ::OpenDDS::DCPS::DCPSInfo_out,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:34

namespace POA_OpenDDS
{
  
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:34

  namespace DCPS
  {
    

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp:72

    

    class DCPSInfo;
    typedef DCPSInfo *DCPSInfo_ptr;

    class OpenDDS_InfoRepoDiscovery_Export DCPSInfo
      : public virtual PortableServer::ServantBase
    {
    protected:
      DCPSInfo (void);
    
    public:
      /// Useful for template programming.
      typedef ::OpenDDS::DCPS::DCPSInfo _stub_type;
      typedef ::OpenDDS::DCPS::DCPSInfo_ptr _stub_ptr_type;
      typedef ::OpenDDS::DCPS::DCPSInfo_var _stub_var_type;

      DCPSInfo (const DCPSInfo& rhs)
#ifdef ACE_HAS_CPP11
        = default
#endif
      ;
      virtual ~DCPSInfo (void);

      virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

      virtual void _dispatch (
          TAO_ServerRequest & req,
          TAO::Portable_Server::Servant_Upcall *servant_upcall);
      
      ::OpenDDS::DCPS::DCPSInfo *_this (void);
      
      virtual const char* _interface_repository_id (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::CORBA::Boolean attach_participant (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId) = 0;

      static void attach_participant_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::OpenDDS::DCPS::TopicStatus assert_topic (
        ::OpenDDS::DCPS::GUID_t_out topicId,
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const char * topicName,
        const char * DataTypeName,
        const ::DDS::TopicQos & qos,
        ::CORBA::Boolean hasDcpsKey) = 0;

      static void assert_topic_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::OpenDDS::DCPS::TopicStatus find_topic (
        ::DDS::DomainId_t domainId,
        const char * topicName,
        ::CORBA::String_out DataTypeName,
        ::DDS::TopicQos_out qos,
        ::OpenDDS::DCPS::GUID_t_out topicId) = 0;

      static void find_topic_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::OpenDDS::DCPS::TopicStatus remove_topic (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & topicId) = 0;

      static void remove_topic_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::OpenDDS::DCPS::GUID_t reserve_publication_id (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & topicId) = 0;

      static void reserve_publication_id_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::CORBA::Boolean add_publication (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & topicId,
        const ::OpenDDS::DCPS::GUID_t & pubId,
        ::OpenDDS::DCPS::DataWriterRemote_ptr publication,
        const ::DDS::DataWriterQos & qos,
        const ::OpenDDS::DCPS::TransportLocatorSeq & transInfo,
        const ::DDS::PublisherQos & publisherQos,
        const ::DDS::OctetSeq & serializedTypeInfo) = 0;

      static void add_publication_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void remove_publication (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & publicationId) = 0;

      static void remove_publication_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::OpenDDS::DCPS::GUID_t reserve_subscription_id (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & topicId) = 0;

      static void reserve_subscription_id_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::CORBA::Boolean add_subscription (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & topicId,
        const ::OpenDDS::DCPS::GUID_t & subId,
        ::OpenDDS::DCPS::DataReaderRemote_ptr subscription,
        const ::DDS::DataReaderQos & qos,
        const ::OpenDDS::DCPS::TransportLocatorSeq & transInfo,
        const ::DDS::SubscriberQos & subscriberQos,
        const char * filterClassName,
        const char * filterExpression,
        const ::DDS::StringSeq & exprParams,
        const ::DDS::OctetSeq & serializedTypeInfo) = 0;

      static void add_subscription_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void remove_subscription (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & subscriptionId) = 0;

      static void remove_subscription_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::OpenDDS::DCPS::AddDomainStatus add_domain_participant (
        ::DDS::DomainId_t domain,
        const ::DDS::DomainParticipantQos & qos) = 0;

      static void add_domain_participant_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void remove_domain_participant (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId) = 0;

      static void remove_domain_participant_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void disassociate_participant (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & local_id,
        const ::OpenDDS::DCPS::GUID_t & remote_id) = 0;

      static void disassociate_participant_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void disassociate_subscription (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & local_id,
        const ::OpenDDS::DCPS::GUID_t & remote_id) = 0;

      static void disassociate_subscription_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void disassociate_publication (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & local_id,
        const ::OpenDDS::DCPS::GUID_t & remote_id) = 0;

      static void disassociate_publication_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void ignore_domain_participant (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & myParticipantId,
        const ::OpenDDS::DCPS::GUID_t & ignoreId) = 0;

      static void ignore_domain_participant_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void ignore_topic (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & myParticipantId,
        const ::OpenDDS::DCPS::GUID_t & ignoreId) = 0;

      static void ignore_topic_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void ignore_subscription (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & myParticipantId,
        const ::OpenDDS::DCPS::GUID_t & ignoreId) = 0;

      static void ignore_subscription_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void ignore_publication (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & myParticipantId,
        const ::OpenDDS::DCPS::GUID_t & ignoreId) = 0;

      static void ignore_publication_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::CORBA::Boolean update_domain_participant_qos (
        ::DDS::DomainId_t domain,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::DDS::DomainParticipantQos & qos) = 0;

      static void update_domain_participant_qos_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::CORBA::Boolean update_topic_qos (
        const ::OpenDDS::DCPS::GUID_t & topicId,
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::DDS::TopicQos & qos) = 0;

      static void update_topic_qos_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::CORBA::Boolean update_publication_qos (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & publicationId,
        const ::DDS::DataWriterQos & qos,
        const ::DDS::PublisherQos & publisherQos) = 0;

      static void update_publication_qos_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::CORBA::Boolean update_subscription_qos (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & subscriptionId,
        const ::DDS::DataReaderQos & qos,
        const ::DDS::SubscriberQos & subscriberQos) = 0;

      static void update_subscription_qos_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::CORBA::Boolean update_subscription_params (
        ::DDS::DomainId_t domainId,
        const ::OpenDDS::DCPS::GUID_t & participantId,
        const ::OpenDDS::DCPS::GUID_t & subscriptionId,
        const ::DDS::StringSeq & exprParams) = 0;

      static void update_subscription_params_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void shutdown (
        void) = 0;

      static void shutdown_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual char * dump_to_string (
        void) = 0;

      static void dump_to_string_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
    };
  
  
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:65

  } // module OpenDDS::DCPS


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:65

} // module OpenDDS

OPENDDS_END_VERSIONED_NAMESPACE_DECL



#include /**/ "ace/post.h"

#endif /* ifndef */

