version: "3.9"

services:
  pub:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: ["/workspaces/testdds/tools/launch.sh", "--config", "/workspaces/testdds/config/test_1to1_normal/pub.json"]
    volumes:
      - ./config:/workspaces/testdds/config
      - ./logs:/workspaces/testdds/logs
    environment:
      LOG_FILE: /workspaces/testdds/logs/pub.log
    networks:
      - dds_test_net

  sub:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: ["/workspaces/testdds/tools/launch.sh", "--config", "/workspaces/testdds/config/test_1to1_normal/sub.json"]
    volumes:
      - ./config:/workspaces/testdds/config
      - ./logs:/workspaces/testdds/logs
    environment:
      LOG_FILE: /workspaces/testdds/logs/sub_${HOSTNAME}.log
    deploy:
      replicas: 3
    networks:
      - dds_test_net

networks:
  dds_test_net: