version: "3.9"

services:
  pub:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: ["/workspaces/fastdds/tools/launch.sh", "--config", "/workspaces/fastdds/config/test_1to1_normal/pub.json"]
    volumes:
      - ./config:/workspaces/fastdds/config
      - ./logs:/workspaces/fastdds/logs
    environment:
      LOG_FILE: /workspaces/fastdds/logs/pub.log
    networks:
      - dds_test_net

  sub:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: ["/workspaces/fastdds/tools/launch.sh", "--config", "/workspaces/fastdds/config/test_1to1_normal/sub.json"]
    volumes:
      - ./config:/workspaces/fastdds/config
      - ./logs:/workspaces/fastdds/logs
    environment:
      LOG_FILE: /workspaces/fastdds/logs/sub_${HOSTNAME}.log
    deploy:
      replicas: 3
    networks:
      - dds_test_net

networks:
  dds_test_net: