// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_DDSDCPSINFOUTILSC_0PHHPP_H_
#define _TAO_IDL_DDSDCPSINFOUTILSC_0PHHPP_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "dds/DCPS/dcps_export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/BD_String_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"
#include /**/ "dds/Versioned_Namespace.h"

#include "dds/DdsDcpsCoreC.h"
#include "dds/DdsDcpsGuidC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 23
#error This file should be regenerated with TAO_IDL
#endif

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



OPENDDS_END_VERSIONED_NAMESPACE_DECL



OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace OpenDDS
{
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

  namespace DCPS
  {
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct MonotonicTime_t;

    typedef
      ::TAO_Fixed_Var_T<
          MonotonicTime_t
        >
      MonotonicTime_t_var;

    typedef
      MonotonicTime_t &
      MonotonicTime_t_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export MonotonicTime_t
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef MonotonicTime_t_var _var_type;
      typedef MonotonicTime_t_out _out_type;
      
      ::CORBA::Long sec;
      ::CORBA::ULong nanosec;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:453

    typedef DDS::OctetSeq TransportBLOB;
    typedef DDS::OctetSeq_var TransportBLOB_var;
    typedef DDS::OctetSeq_out TransportBLOB_out;
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct TransportLocator;

    typedef
      ::TAO_Var_Var_T<
          TransportLocator
        >
      TransportLocator_var;

    typedef
      ::TAO_Out_T<
          TransportLocator
        >
      TransportLocator_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export TransportLocator
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TransportLocator_var _var_type;
      typedef TransportLocator_out _out_type;
      
      ::TAO::String_Manager transport_type;
      OpenDDS::DCPS::TransportBLOB data;
    };

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

    

#if !defined (_OPENDDS_DCPS_TRANSPORTLOCATORSEQ_CH_)
#define _OPENDDS_DCPS_TRANSPORTLOCATORSEQ_CH_

    class TransportLocatorSeq;
    typedef ::TAO_VarSeq_Var_T<TransportLocatorSeq> TransportLocatorSeq_var;
    typedef ::TAO_Seq_Out_T<TransportLocatorSeq> TransportLocatorSeq_out;
    

    class OpenDDS_Dcps_Export TransportLocatorSeq
      : public
          ::TAO::unbounded_value_sequence< TransportLocator>
    {
    public:
      TransportLocatorSeq (void);
      TransportLocatorSeq ( ::CORBA::ULong max);
      TransportLocatorSeq (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        TransportLocator* buffer,
        ::CORBA::Boolean release = false);
#if defined (ACE_HAS_CPP11)
      TransportLocatorSeq (const TransportLocatorSeq &) = default;
      TransportLocatorSeq (TransportLocatorSeq &&) = default;
      TransportLocatorSeq& operator= (const TransportLocatorSeq &) = default;
      TransportLocatorSeq& operator= (TransportLocatorSeq &&) = default;
#endif /* ACE_HAS_CPP11 */
      virtual ~TransportLocatorSeq (void);
      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TransportLocatorSeq_var _var_type;
      typedef TransportLocatorSeq_out _out_type;
    };

#endif /* end #if !defined */
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct IncompatibleQosStatus;

    typedef
      ::TAO_Var_Var_T<
          IncompatibleQosStatus
        >
      IncompatibleQosStatus_var;

    typedef
      ::TAO_Out_T<
          IncompatibleQosStatus
        >
      IncompatibleQosStatus_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export IncompatibleQosStatus
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef IncompatibleQosStatus_var _var_type;
      typedef IncompatibleQosStatus_out _out_type;
      
      ::CORBA::Long total_count;
      ::CORBA::Long count_since_last_send;
      DDS::QosPolicyId_t last_policy_id;
      DDS::QosPolicyCountSeq policies;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct AddDomainStatus;

    typedef
      ::TAO_Fixed_Var_T<
          AddDomainStatus
        >
      AddDomainStatus_var;

    typedef
      AddDomainStatus &
      AddDomainStatus_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export AddDomainStatus
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef AddDomainStatus_var _var_type;
      typedef AddDomainStatus_out _out_type;
      
      OpenDDS::DCPS::GUID_t id;
      ::CORBA::Boolean federated;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/enum_ch.cpp:43

    enum TopicStatus
    {
      CREATED,
      ENABLED,
      FOUND,
      NOT_FOUND,
      REMOVED,
      CONFLICTING_TYPENAME,
      PRECONDITION_NOT_MET,
      INTERNAL_ERROR,
      TOPIC_DISABLED
    };

    typedef TopicStatus &TopicStatus_out;
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct WriterAssociation;

    typedef
      ::TAO_Var_Var_T<
          WriterAssociation
        >
      WriterAssociation_var;

    typedef
      ::TAO_Out_T<
          WriterAssociation
        >
      WriterAssociation_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export WriterAssociation
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef WriterAssociation_var _var_type;
      typedef WriterAssociation_out _out_type;
      
      OpenDDS::DCPS::TransportLocatorSeq writerTransInfo;
      OpenDDS::DCPS::TransportLocator writerDiscInfo;
      ::CORBA::ULong transportContext;
      OpenDDS::DCPS::GUID_t writerId;
      DDS::PublisherQos pubQos;
      DDS::DataWriterQos writerQos;
      DDS::OctetSeq serializedTypeInfo;
      OpenDDS::DCPS::MonotonicTime_t participantDiscoveredAt;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct ReaderAssociation;

    typedef
      ::TAO_Var_Var_T<
          ReaderAssociation
        >
      ReaderAssociation_var;

    typedef
      ::TAO_Out_T<
          ReaderAssociation
        >
      ReaderAssociation_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export ReaderAssociation
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef ReaderAssociation_var _var_type;
      typedef ReaderAssociation_out _out_type;
      
      OpenDDS::DCPS::TransportLocatorSeq readerTransInfo;
      OpenDDS::DCPS::TransportLocator readerDiscInfo;
      ::CORBA::ULong transportContext;
      OpenDDS::DCPS::GUID_t readerId;
      DDS::SubscriberQos subQos;
      DDS::DataReaderQos readerQos;
      ::TAO::String_Manager filterClassName;
      ::TAO::String_Manager filterExpression;
      DDS::StringSeq exprParams;
      DDS::OctetSeq serializedTypeInfo;
      OpenDDS::DCPS::MonotonicTime_t participantDiscoveredAt;
    };

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

    

#if !defined (_OPENDDS_DCPS_WRITERIDSEQ_CH_)
#define _OPENDDS_DCPS_WRITERIDSEQ_CH_

    class WriterIdSeq;
    typedef ::TAO_FixedSeq_Var_T<WriterIdSeq> WriterIdSeq_var;
    typedef ::TAO_Seq_Out_T<WriterIdSeq> WriterIdSeq_out;
    

    class OpenDDS_Dcps_Export WriterIdSeq
      : public
          ::TAO::unbounded_value_sequence< GUID_t>
    {
    public:
      WriterIdSeq (void);
      WriterIdSeq ( ::CORBA::ULong max);
      WriterIdSeq (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        GUID_t* buffer,
        ::CORBA::Boolean release = false);
#if defined (ACE_HAS_CPP11)
      WriterIdSeq (const WriterIdSeq &) = default;
      WriterIdSeq (WriterIdSeq &&) = default;
      WriterIdSeq& operator= (const WriterIdSeq &) = default;
      WriterIdSeq& operator= (WriterIdSeq &&) = default;
#endif /* ACE_HAS_CPP11 */
      virtual ~WriterIdSeq (void);
      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef WriterIdSeq_var _var_type;
      typedef WriterIdSeq_out _out_type;
    };

#endif /* end #if !defined */

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

    

#if !defined (_OPENDDS_DCPS_READERIDSEQ_CH_)
#define _OPENDDS_DCPS_READERIDSEQ_CH_

    class ReaderIdSeq;
    typedef ::TAO_FixedSeq_Var_T<ReaderIdSeq> ReaderIdSeq_var;
    typedef ::TAO_Seq_Out_T<ReaderIdSeq> ReaderIdSeq_out;
    

    class OpenDDS_Dcps_Export ReaderIdSeq
      : public
          ::TAO::unbounded_value_sequence< GUID_t>
    {
    public:
      ReaderIdSeq (void);
      ReaderIdSeq ( ::CORBA::ULong max);
      ReaderIdSeq (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        GUID_t* buffer,
        ::CORBA::Boolean release = false);
#if defined (ACE_HAS_CPP11)
      ReaderIdSeq (const ReaderIdSeq &) = default;
      ReaderIdSeq (ReaderIdSeq &&) = default;
      ReaderIdSeq& operator= (const ReaderIdSeq &) = default;
      ReaderIdSeq& operator= (ReaderIdSeq &&) = default;
#endif /* ACE_HAS_CPP11 */
      virtual ~ReaderIdSeq (void);
      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef ReaderIdSeq_var _var_type;
      typedef ReaderIdSeq_out _out_type;
    };

#endif /* end #if !defined */
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:395

    typedef char * String256;
    typedef ::CORBA::String_var String256_var;
    typedef ::CORBA::String_out String256_out;
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct ContentFilterProperty_t;

    typedef
      ::TAO_Var_Var_T<
          ContentFilterProperty_t
        >
      ContentFilterProperty_t_var;

    typedef
      ::TAO_Out_T<
          ContentFilterProperty_t
        >
      ContentFilterProperty_t_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export ContentFilterProperty_t
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef ContentFilterProperty_t_var _var_type;
      typedef ContentFilterProperty_t_out _out_type;
      
      ::TAO::String_Manager contentFilteredTopicName;
      ::TAO::String_Manager relatedTopicName;
      ::TAO::String_Manager filterClassName;
      ::TAO::String_Manager filterExpression;
      DDS::StringSeq expressionParameters;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct ReaderProxy_t;

    typedef
      ::TAO_Var_Var_T<
          ReaderProxy_t
        >
      ReaderProxy_t_var;

    typedef
      ::TAO_Out_T<
          ReaderProxy_t
        >
      ReaderProxy_t_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export ReaderProxy_t
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef ReaderProxy_t_var _var_type;
      typedef ReaderProxy_t_out _out_type;
      
      OpenDDS::DCPS::GUID_t remoteReaderGuid;
      ::CORBA::Boolean expectsInlineQos;
      OpenDDS::DCPS::TransportLocatorSeq allLocators;
      OpenDDS::DCPS::GUIDSeq associatedWriters;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DiscoveredReaderData;

    typedef
      ::TAO_Var_Var_T<
          DiscoveredReaderData
        >
      DiscoveredReaderData_var;

    typedef
      ::TAO_Out_T<
          DiscoveredReaderData
        >
      DiscoveredReaderData_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export DiscoveredReaderData
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DiscoveredReaderData_var _var_type;
      typedef DiscoveredReaderData_out _out_type;
      
      DDS::SubscriptionBuiltinTopicData ddsSubscriptionData;
      OpenDDS::DCPS::ReaderProxy_t readerProxy;
      OpenDDS::DCPS::ContentFilterProperty_t contentFilterProperty;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct WriterProxy_t;

    typedef
      ::TAO_Var_Var_T<
          WriterProxy_t
        >
      WriterProxy_t_var;

    typedef
      ::TAO_Out_T<
          WriterProxy_t
        >
      WriterProxy_t_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export WriterProxy_t
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef WriterProxy_t_var _var_type;
      typedef WriterProxy_t_out _out_type;
      
      OpenDDS::DCPS::GUID_t remoteWriterGuid;
      OpenDDS::DCPS::TransportLocatorSeq allLocators;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DiscoveredWriterData;

    typedef
      ::TAO_Var_Var_T<
          DiscoveredWriterData
        >
      DiscoveredWriterData_var;

    typedef
      ::TAO_Out_T<
          DiscoveredWriterData
        >
      DiscoveredWriterData_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Dcps_Export DiscoveredWriterData
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DiscoveredWriterData_var _var_type;
      typedef DiscoveredWriterData_out _out_type;
      
      DDS::PublicationBuiltinTopicData ddsPublicationData;
      OpenDDS::DCPS::WriterProxy_t writerProxy;
    };
  
  
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62

  
  } // module OpenDDS::DCPS


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module OpenDDS
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::MonotonicTime_t>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::MonotonicTime_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::TransportLocator>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::TransportLocator,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::TransportLocatorSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::TransportLocatorSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::IncompatibleQosStatus>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::IncompatibleQosStatus,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::AddDomainStatus>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::AddDomainStatus,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:890

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::TopicStatus>
    : public
        Basic_Arg_Traits_T<
            ::OpenDDS::DCPS::TopicStatus,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::WriterAssociation>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::WriterAssociation,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::ReaderAssociation>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::ReaderAssociation,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::WriterIdSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::WriterIdSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::ReaderIdSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::ReaderIdSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_STRING256256__ARG_TRAITS_)
#define _STRING256256__ARG_TRAITS_

  struct String256_256 {};

  template<>
  class Arg_Traits<String256_256>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            256,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::ContentFilterProperty_t>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::ContentFilterProperty_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::ReaderProxy_t>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::ReaderProxy_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::DiscoveredReaderData>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::DiscoveredReaderData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::WriterProxy_t>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::WriterProxy_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::DCPS::DiscoveredWriterData>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::DCPS::DiscoveredWriterData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::MonotonicTime_t &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::MonotonicTime_t &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::TransportLocator &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::TransportLocator &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_OpenDDS_DCPS_TransportLocatorSeq_H_
#define _TAO_CDR_OP_OpenDDS_DCPS_TransportLocatorSeq_H_

OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::DCPS::TransportLocatorSeq &_tao_sequence);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::DCPS::TransportLocatorSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




#endif /* _TAO_CDR_OP_OpenDDS_DCPS_TransportLocatorSeq_H_ */
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::IncompatibleQosStatus &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::IncompatibleQosStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::AddDomainStatus &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::AddDomainStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/cdr_op_ch.cpp:33



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, OpenDDS::DCPS::TopicStatus _tao_enumerator);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &strm, OpenDDS::DCPS::TopicStatus &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::WriterAssociation &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::WriterAssociation &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::ReaderAssociation &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::ReaderAssociation &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_OpenDDS_DCPS_WriterIdSeq_H_
#define _TAO_CDR_OP_OpenDDS_DCPS_WriterIdSeq_H_

OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::DCPS::WriterIdSeq &_tao_sequence);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::DCPS::WriterIdSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




#endif /* _TAO_CDR_OP_OpenDDS_DCPS_WriterIdSeq_H_ */
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_OpenDDS_DCPS_ReaderIdSeq_H_
#define _TAO_CDR_OP_OpenDDS_DCPS_ReaderIdSeq_H_

OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::DCPS::ReaderIdSeq &_tao_sequence);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::DCPS::ReaderIdSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




#endif /* _TAO_CDR_OP_OpenDDS_DCPS_ReaderIdSeq_H_ */
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::ContentFilterProperty_t &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::ContentFilterProperty_t &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::ReaderProxy_t &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::ReaderProxy_t &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::DiscoveredReaderData &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::DiscoveredReaderData &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::WriterProxy_t &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::WriterProxy_t &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::DCPS::DiscoveredWriterData &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::DCPS::DiscoveredWriterData &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1649



OPENDDS_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "DdsDcpsInfoUtilsC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

