// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_array/array_ci.cpp:146




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


ACE_INLINE
void
TAO::Array_Traits<DDS::OctetArray16_forany>::free (
    DDS::OctetArray16_slice * _tao_slice)
{
  DDS::OctetArray16_free (_tao_slice);
}

ACE_INLINE
DDS::OctetArray16_slice *
TAO::Array_Traits<DDS::OctetArray16_forany>::dup (
    const DDS::OctetArray16_slice * _tao_slice)
{
  return DDS::OctetArray16_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<DDS::OctetArray16_forany>::copy (
    DDS::OctetArray16_slice * _tao_to,
    const DDS::OctetArray16_slice * _tao_from)
{
  DDS::OctetArray16_copy (_tao_to, _tao_from);
}

ACE_INLINE
void
TAO::Array_Traits<DDS::OctetArray16_forany>::zero (
    DDS::OctetArray16_slice * _tao_slice)
{
  // Zero each individual element.
  for ( ::CORBA::ULong i0 = 0; i0 < 16; ++i0)
    {
      _tao_slice[i0] = ::CORBA::Octet ();
    }
}

ACE_INLINE
DDS::OctetArray16_slice *
TAO::Array_Traits<DDS::OctetArray16_forany>::alloc (void)
{
  return DDS::OctetArray16_alloc ();
}


TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




OPENDDS_END_VERSIONED_NAMESPACE_DECL


