// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_ci.cpp:43

ACE_INLINE
DDS::AnnotationDescriptor::AnnotationDescriptor (void)
{}

ACE_INLINE const char*
DDS::AnnotationDescriptor::_tao_obv_static_repository_id ()
{
  return "IDL:DDS/AnnotationDescriptor:1.0";
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_ci.cpp:43

ACE_INLINE
DDS::VerbatimTextDescriptor::VerbatimTextDescriptor (void)
{}

ACE_INLINE const char*
DDS::VerbatimTextDescriptor::_tao_obv_static_repository_id ()
{
  return "IDL:DDS/VerbatimTextDescriptor:1.0";
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_ci.cpp:43

ACE_INLINE
DDS::TypeDescriptor::TypeDescriptor (void)
{}

ACE_INLINE const char*
DDS::TypeDescriptor::_tao_obv_static_repository_id ()
{
  return "IDL:DDS/TypeDescriptor:1.0";
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_ci.cpp:43

ACE_INLINE
DDS::MemberDescriptor::MemberDescriptor (void)
{}

ACE_INLINE const char*
DDS::MemberDescriptor::_tao_obv_static_repository_id ()
{
  return "IDL:DDS/MemberDescriptor:1.0";
}


OPENDDS_END_VERSIONED_NAMESPACE_DECL


