// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_DDSDCPSTYPESUPPORTEXTC_0HP4PB_H_
#define _TAO_IDL_DDSDCPSTYPESUPPORTEXTC_0HP4PB_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "dds/DCPS/dcps_export.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"
#include /**/ "dds/Versioned_Namespace.h"

#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 23
#error This file should be regenerated with TAO_IDL
#endif

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



OPENDDS_END_VERSIONED_NAMESPACE_DECL



OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace OpenDDS
{
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

  namespace DCPS
  {
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

    

#if !defined (_OPENDDS_DCPS_REPRESENTATIONFORMAT__VAR_OUT_CH_)
#define _OPENDDS_DCPS_REPRESENTATIONFORMAT__VAR_OUT_CH_

    class RepresentationFormat;
    typedef RepresentationFormat *RepresentationFormat_ptr;
    typedef TAO_Objref_Var_T<RepresentationFormat> RepresentationFormat_var;
    typedef TAO_Objref_Out_T<RepresentationFormat> RepresentationFormat_out;
    

#endif /* end #if !defined */

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

    

    class OpenDDS_Dcps_Export RepresentationFormat
      : public virtual ::CORBA::Object
    {
    public:
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      typedef RepresentationFormat_ptr _ptr_type;
      typedef RepresentationFormat_var _var_type;
      typedef RepresentationFormat_out _out_type;

      // The static operations.
      static RepresentationFormat_ptr _duplicate (RepresentationFormat_ptr obj);

      static void _tao_release (RepresentationFormat_ptr obj);

      static RepresentationFormat_ptr _narrow (::CORBA::Object_ptr obj);
      static RepresentationFormat_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
      static RepresentationFormat_ptr _nil (void);

      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

      

      virtual ::CORBA::Boolean _is_a (const char *type_id);
      virtual const char* _interface_repository_id (void) const;
      virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
    
    protected:
      // Abstract or local interface only.
      RepresentationFormat (void);

      

      virtual ~RepresentationFormat (void);
    
    private:
      // Private and unimplemented for concrete interfaces.
      ACE_UNIMPLEMENTED_FUNC (RepresentationFormat (const RepresentationFormat &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (RepresentationFormat (RepresentationFormat &&))
#endif /* ACE_HAS_CPP11 */
      ACE_UNIMPLEMENTED_FUNC (RepresentationFormat &operator= (const RepresentationFormat &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (RepresentationFormat &operator= (RepresentationFormat &&))
#endif /* ACE_HAS_CPP11 */
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

    

#if !defined (_OPENDDS_DCPS_CDRREPRESENTATIONFORMAT__VAR_OUT_CH_)
#define _OPENDDS_DCPS_CDRREPRESENTATIONFORMAT__VAR_OUT_CH_

    class CdrRepresentationFormat;
    typedef CdrRepresentationFormat *CdrRepresentationFormat_ptr;
    typedef TAO_Objref_Var_T<CdrRepresentationFormat> CdrRepresentationFormat_var;
    typedef TAO_Objref_Out_T<CdrRepresentationFormat> CdrRepresentationFormat_out;
    

#endif /* end #if !defined */

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

    

    class OpenDDS_Dcps_Export CdrRepresentationFormat
      : public virtual ::OpenDDS::DCPS::RepresentationFormat
    
    {
    public:
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      typedef CdrRepresentationFormat_ptr _ptr_type;
      typedef CdrRepresentationFormat_var _var_type;
      typedef CdrRepresentationFormat_out _out_type;

      // The static operations.
      static CdrRepresentationFormat_ptr _duplicate (CdrRepresentationFormat_ptr obj);

      static void _tao_release (CdrRepresentationFormat_ptr obj);

      static CdrRepresentationFormat_ptr _narrow (::CORBA::Object_ptr obj);
      static CdrRepresentationFormat_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
      static CdrRepresentationFormat_ptr _nil (void);

      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

      

      virtual ::CORBA::Boolean _is_a (const char *type_id);
      virtual const char* _interface_repository_id (void) const;
      virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
    
    protected:
      // Abstract or local interface only.
      CdrRepresentationFormat (void);

      

      virtual ~CdrRepresentationFormat (void);
    
    private:
      // Private and unimplemented for concrete interfaces.
      ACE_UNIMPLEMENTED_FUNC (CdrRepresentationFormat (const CdrRepresentationFormat &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (CdrRepresentationFormat (CdrRepresentationFormat &&))
#endif /* ACE_HAS_CPP11 */
      ACE_UNIMPLEMENTED_FUNC (CdrRepresentationFormat &operator= (const CdrRepresentationFormat &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (CdrRepresentationFormat &operator= (CdrRepresentationFormat &&))
#endif /* ACE_HAS_CPP11 */
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

    

#if !defined (_OPENDDS_DCPS_JSONREPRESENTATIONFORMAT__VAR_OUT_CH_)
#define _OPENDDS_DCPS_JSONREPRESENTATIONFORMAT__VAR_OUT_CH_

    class JsonRepresentationFormat;
    typedef JsonRepresentationFormat *JsonRepresentationFormat_ptr;
    typedef TAO_Objref_Var_T<JsonRepresentationFormat> JsonRepresentationFormat_var;
    typedef TAO_Objref_Out_T<JsonRepresentationFormat> JsonRepresentationFormat_out;
    

#endif /* end #if !defined */

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

    

    class OpenDDS_Dcps_Export JsonRepresentationFormat
      : public virtual ::OpenDDS::DCPS::RepresentationFormat
    
    {
    public:
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      typedef JsonRepresentationFormat_ptr _ptr_type;
      typedef JsonRepresentationFormat_var _var_type;
      typedef JsonRepresentationFormat_out _out_type;

      // The static operations.
      static JsonRepresentationFormat_ptr _duplicate (JsonRepresentationFormat_ptr obj);

      static void _tao_release (JsonRepresentationFormat_ptr obj);

      static JsonRepresentationFormat_ptr _narrow (::CORBA::Object_ptr obj);
      static JsonRepresentationFormat_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
      static JsonRepresentationFormat_ptr _nil (void);

      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

      

      virtual ::CORBA::Boolean _is_a (const char *type_id);
      virtual const char* _interface_repository_id (void) const;
      virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
    
    protected:
      // Abstract or local interface only.
      JsonRepresentationFormat (void);

      

      virtual ~JsonRepresentationFormat (void);
    
    private:
      // Private and unimplemented for concrete interfaces.
      ACE_UNIMPLEMENTED_FUNC (JsonRepresentationFormat (const JsonRepresentationFormat &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (JsonRepresentationFormat (JsonRepresentationFormat &&))
#endif /* ACE_HAS_CPP11 */
      ACE_UNIMPLEMENTED_FUNC (JsonRepresentationFormat &operator= (const JsonRepresentationFormat &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (JsonRepresentationFormat &operator= (JsonRepresentationFormat &&))
#endif /* ACE_HAS_CPP11 */
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

    

#if !defined (_OPENDDS_DCPS_TYPESUPPORT__VAR_OUT_CH_)
#define _OPENDDS_DCPS_TYPESUPPORT__VAR_OUT_CH_

    class TypeSupport;
    typedef TypeSupport *TypeSupport_ptr;
    typedef TAO_Objref_Var_T<TypeSupport> TypeSupport_var;
    typedef TAO_Objref_Out_T<TypeSupport> TypeSupport_out;
    

#endif /* end #if !defined */

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

    

    class OpenDDS_Dcps_Export TypeSupport
      : public virtual ::DDS::TypeSupport
    
    {
    public:
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      typedef TypeSupport_ptr _ptr_type;
      typedef TypeSupport_var _var_type;
      typedef TypeSupport_out _out_type;

      // The static operations.
      static TypeSupport_ptr _duplicate (TypeSupport_ptr obj);

      static void _tao_release (TypeSupport_ptr obj);

      static TypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
      static TypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
      static TypeSupport_ptr _nil (void);

      virtual ::DDS::DataWriter_ptr create_datawriter (
        void) = 0;

      virtual ::DDS::DataReader_ptr create_datareader (
        void) = 0;

      virtual ::DDS::DataReader_ptr create_multitopic_datareader (
        void) = 0;

      virtual ::CORBA::Boolean has_dcps_key (
        void) = 0;

      virtual ::DDS::ReturnCode_t unregister_type (
        ::DDS::DomainParticipant_ptr domain,
        const char * type_name) = 0;

      virtual void representations_allowed_by_type (
        ::DDS::DataRepresentationIdSeq & seq) = 0;

      virtual ::OpenDDS::DCPS::RepresentationFormat_ptr make_format (
        ::DDS::DataRepresentationId_t representation) = 0;

      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

      

      virtual ::CORBA::Boolean _is_a (const char *type_id);
      virtual const char* _interface_repository_id (void) const;
      virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
    
    protected:
      // Abstract or local interface only.
      TypeSupport (void);

      

      virtual ~TypeSupport (void);
    
    private:
      // Private and unimplemented for concrete interfaces.
      ACE_UNIMPLEMENTED_FUNC (TypeSupport (const TypeSupport &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (TypeSupport (TypeSupport &&))
#endif /* ACE_HAS_CPP11 */
      ACE_UNIMPLEMENTED_FUNC (TypeSupport &operator= (const TypeSupport &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (TypeSupport &operator= (TypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    };
  
  
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62

  
  } // module OpenDDS::DCPS


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module OpenDDS
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_OPENDDS_DCPS_REPRESENTATIONFORMAT__TRAITS_)
#define _OPENDDS_DCPS_REPRESENTATIONFORMAT__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::OpenDDS::DCPS::RepresentationFormat>
  {
    static ::OpenDDS::DCPS::RepresentationFormat_ptr duplicate (
        ::OpenDDS::DCPS::RepresentationFormat_ptr p);
    static void release (
        ::OpenDDS::DCPS::RepresentationFormat_ptr p);
    static ::OpenDDS::DCPS::RepresentationFormat_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::OpenDDS::DCPS::RepresentationFormat_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_OPENDDS_DCPS_CDRREPRESENTATIONFORMAT__TRAITS_)
#define _OPENDDS_DCPS_CDRREPRESENTATIONFORMAT__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::OpenDDS::DCPS::CdrRepresentationFormat>
  {
    static ::OpenDDS::DCPS::CdrRepresentationFormat_ptr duplicate (
        ::OpenDDS::DCPS::CdrRepresentationFormat_ptr p);
    static void release (
        ::OpenDDS::DCPS::CdrRepresentationFormat_ptr p);
    static ::OpenDDS::DCPS::CdrRepresentationFormat_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::OpenDDS::DCPS::CdrRepresentationFormat_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_OPENDDS_DCPS_JSONREPRESENTATIONFORMAT__TRAITS_)
#define _OPENDDS_DCPS_JSONREPRESENTATIONFORMAT__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::OpenDDS::DCPS::JsonRepresentationFormat>
  {
    static ::OpenDDS::DCPS::JsonRepresentationFormat_ptr duplicate (
        ::OpenDDS::DCPS::JsonRepresentationFormat_ptr p);
    static void release (
        ::OpenDDS::DCPS::JsonRepresentationFormat_ptr p);
    static ::OpenDDS::DCPS::JsonRepresentationFormat_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::OpenDDS::DCPS::JsonRepresentationFormat_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_OPENDDS_DCPS_TYPESUPPORT__TRAITS_)
#define _OPENDDS_DCPS_TYPESUPPORT__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::OpenDDS::DCPS::TypeSupport>
  {
    static ::OpenDDS::DCPS::TypeSupport_ptr duplicate (
        ::OpenDDS::DCPS::TypeSupport_ptr p);
    static void release (
        ::OpenDDS::DCPS::TypeSupport_ptr p);
    static ::OpenDDS::DCPS::TypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::OpenDDS::DCPS::TypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1649



OPENDDS_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "DdsDcpsTypeSupportExtC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

