/* -*- C++ -*- */
/* Generated by /workspaces/testdds/lib/OpenDDS/OpenDDS/bin/opendds_idl version 3.34.0-dev (ACE version 6.5.23) running on input file DdsDynamicDataSeq.idl */
#ifndef OPENDDS_IDL_GENERATED_DDSDYNAMICDATASEQTYPESUPPORTIMPL_H_F0PMES
#define OPENDDS_IDL_GENERATED_DDSDYNAMICDATASEQTYPESUPPORTIMPL_H_F0PMES

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 34, 0)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "DdsDynamicDataSeqC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"
#include "tao/BooleanSeqC.h"
#include "tao/CharSeqC.h"
#include "tao/DoubleSeqC.h"
#include "tao/FloatSeqC.h"
#include "tao/Int8SeqC.h"
#include "tao/LongDoubleSeqC.h"
#include "tao/LongLongSeqC.h"
#include "tao/LongSeqC.h"
#include "tao/OctetSeqC.h"
#include "tao/ShortSeqC.h"
#include "tao/StringSeqC.h"
#include "tao/UInt8SeqC.h"
#include "tao/ULongLongSeqC.h"
#include "tao/ULongSeqC.h"
#include "tao/UShortSeqC.h"
#include "tao/WCharSeqC.h"
#include "tao/WStringSeqC.h"
#include "dds/DCPS/dcps_export.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: LongSeq */


/* End TYPEDEF: LongSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: ULongSeq */


/* End TYPEDEF: ULongSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: Int8Seq */


/* End TYPEDEF: Int8Seq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: UInt8Seq */


/* End TYPEDEF: UInt8Seq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: ShortSeq */


/* End TYPEDEF: ShortSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: UShortSeq */


/* End TYPEDEF: UShortSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: LongLongSeq */


/* End TYPEDEF: LongLongSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: ULongLongSeq */


/* End TYPEDEF: ULongLongSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: FloatSeq */


/* End TYPEDEF: FloatSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: DoubleSeq */


/* End TYPEDEF: DoubleSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: LongDoubleSeq */


/* End TYPEDEF: LongDoubleSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: CharSeq */


/* End TYPEDEF: CharSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: WCharSeq */


/* End TYPEDEF: WCharSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: OctetSeq */


/* End TYPEDEF: OctetSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: BooleanSeq */


/* End TYPEDEF: BooleanSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: StringSeq */


/* End TYPEDEF: StringSeq */

/* End MODULE: CORBA */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: WStringSeq */


/* End TYPEDEF: WStringSeq */

/* End MODULE: CORBA */


/* Begin MODULE: DDS */



/* Begin TYPEDEF: Int32Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_Int32Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_Int32Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_Int32Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::Int32Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::Int32Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::Int32Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::Int32Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Int32Seq,  ::DDS::Int32Seq>(DDS::DynamicType_ptr type, const  ::DDS::Int32Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Int32Seq,  ::DDS::Int32Seq>(DDS::DynamicType_ptr type,  ::DDS::Int32Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::Int32Seq* get_dynamic_data_adapter_value< ::DDS::Int32Seq,  ::DDS::Int32Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: Int32Seq */


/* Begin TYPEDEF: UInt32Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_UInt32Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_UInt32Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_UInt32Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::UInt32Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::UInt32Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::UInt32Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::UInt32Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::UInt32Seq,  ::DDS::UInt32Seq>(DDS::DynamicType_ptr type, const  ::DDS::UInt32Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::UInt32Seq,  ::DDS::UInt32Seq>(DDS::DynamicType_ptr type,  ::DDS::UInt32Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::UInt32Seq* get_dynamic_data_adapter_value< ::DDS::UInt32Seq,  ::DDS::UInt32Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: UInt32Seq */


/* Begin TYPEDEF: Int8Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_Int8Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_Int8Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_Int8Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::Int8Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::Int8Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::Int8Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::Int8Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Int8Seq,  ::DDS::Int8Seq>(DDS::DynamicType_ptr type, const  ::DDS::Int8Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Int8Seq,  ::DDS::Int8Seq>(DDS::DynamicType_ptr type,  ::DDS::Int8Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::Int8Seq* get_dynamic_data_adapter_value< ::DDS::Int8Seq,  ::DDS::Int8Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: Int8Seq */


/* Begin TYPEDEF: UInt8Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_UInt8Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_UInt8Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_UInt8Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::UInt8Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::UInt8Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::UInt8Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::UInt8Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::UInt8Seq,  ::DDS::UInt8Seq>(DDS::DynamicType_ptr type, const  ::DDS::UInt8Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::UInt8Seq,  ::DDS::UInt8Seq>(DDS::DynamicType_ptr type,  ::DDS::UInt8Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::UInt8Seq* get_dynamic_data_adapter_value< ::DDS::UInt8Seq,  ::DDS::UInt8Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: UInt8Seq */


/* Begin TYPEDEF: Int16Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_Int16Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_Int16Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_Int16Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::Int16Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::Int16Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::Int16Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::Int16Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Int16Seq,  ::DDS::Int16Seq>(DDS::DynamicType_ptr type, const  ::DDS::Int16Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Int16Seq,  ::DDS::Int16Seq>(DDS::DynamicType_ptr type,  ::DDS::Int16Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::Int16Seq* get_dynamic_data_adapter_value< ::DDS::Int16Seq,  ::DDS::Int16Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: Int16Seq */


/* Begin TYPEDEF: UInt16Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_UInt16Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_UInt16Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_UInt16Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::UInt16Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::UInt16Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::UInt16Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::UInt16Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::UInt16Seq,  ::DDS::UInt16Seq>(DDS::DynamicType_ptr type, const  ::DDS::UInt16Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::UInt16Seq,  ::DDS::UInt16Seq>(DDS::DynamicType_ptr type,  ::DDS::UInt16Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::UInt16Seq* get_dynamic_data_adapter_value< ::DDS::UInt16Seq,  ::DDS::UInt16Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: UInt16Seq */


/* Begin TYPEDEF: Int64Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_Int64Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_Int64Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_Int64Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::Int64Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::Int64Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::Int64Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::Int64Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Int64Seq,  ::DDS::Int64Seq>(DDS::DynamicType_ptr type, const  ::DDS::Int64Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Int64Seq,  ::DDS::Int64Seq>(DDS::DynamicType_ptr type,  ::DDS::Int64Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::Int64Seq* get_dynamic_data_adapter_value< ::DDS::Int64Seq,  ::DDS::Int64Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: Int64Seq */


/* Begin TYPEDEF: UInt64Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_UInt64Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_UInt64Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_UInt64Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::UInt64Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::UInt64Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::UInt64Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::UInt64Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::UInt64Seq,  ::DDS::UInt64Seq>(DDS::DynamicType_ptr type, const  ::DDS::UInt64Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::UInt64Seq,  ::DDS::UInt64Seq>(DDS::DynamicType_ptr type,  ::DDS::UInt64Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::UInt64Seq* get_dynamic_data_adapter_value< ::DDS::UInt64Seq,  ::DDS::UInt64Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: UInt64Seq */


/* Begin TYPEDEF: Float32Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_Float32Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_Float32Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_Float32Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::Float32Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::Float32Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::Float32Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::Float32Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Float32Seq,  ::DDS::Float32Seq>(DDS::DynamicType_ptr type, const  ::DDS::Float32Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Float32Seq,  ::DDS::Float32Seq>(DDS::DynamicType_ptr type,  ::DDS::Float32Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::Float32Seq* get_dynamic_data_adapter_value< ::DDS::Float32Seq,  ::DDS::Float32Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: Float32Seq */


/* Begin TYPEDEF: Float64Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_Float64Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_Float64Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_Float64Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::Float64Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::Float64Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::Float64Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::Float64Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Float64Seq,  ::DDS::Float64Seq>(DDS::DynamicType_ptr type, const  ::DDS::Float64Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Float64Seq,  ::DDS::Float64Seq>(DDS::DynamicType_ptr type,  ::DDS::Float64Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::Float64Seq* get_dynamic_data_adapter_value< ::DDS::Float64Seq,  ::DDS::Float64Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: Float64Seq */


/* Begin TYPEDEF: Float128Seq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_Float128Seq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_Float128Seq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_Float128Seq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::Float128Seq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::Float128Seq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::Float128Seq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::Float128Seq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Float128Seq,  ::DDS::Float128Seq>(DDS::DynamicType_ptr type, const  ::DDS::Float128Seq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::Float128Seq,  ::DDS::Float128Seq>(DDS::DynamicType_ptr type,  ::DDS::Float128Seq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::Float128Seq* get_dynamic_data_adapter_value< ::DDS::Float128Seq,  ::DDS::Float128Seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: Float128Seq */


/* Begin TYPEDEF: CharSeq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_CharSeq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_CharSeq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_CharSeq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::CharSeq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::CharSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::CharSeq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::CharSeq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::CharSeq,  ::DDS::CharSeq>(DDS::DynamicType_ptr type, const  ::DDS::CharSeq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::CharSeq,  ::DDS::CharSeq>(DDS::DynamicType_ptr type,  ::DDS::CharSeq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::CharSeq* get_dynamic_data_adapter_value< ::DDS::CharSeq,  ::DDS::CharSeq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: CharSeq */


/* Begin TYPEDEF: WcharSeq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_WcharSeq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_WcharSeq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_WcharSeq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::WcharSeq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::WcharSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::WcharSeq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::WcharSeq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::WcharSeq,  ::DDS::WcharSeq>(DDS::DynamicType_ptr type, const  ::DDS::WcharSeq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::WcharSeq,  ::DDS::WcharSeq>(DDS::DynamicType_ptr type,  ::DDS::WcharSeq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::WcharSeq* get_dynamic_data_adapter_value< ::DDS::WcharSeq,  ::DDS::WcharSeq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: WcharSeq */


/* Begin TYPEDEF: BooleanSeq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_BooleanSeq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_BooleanSeq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_BooleanSeq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::BooleanSeq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::BooleanSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::BooleanSeq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::BooleanSeq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::BooleanSeq,  ::DDS::BooleanSeq>(DDS::DynamicType_ptr type, const  ::DDS::BooleanSeq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::BooleanSeq,  ::DDS::BooleanSeq>(DDS::DynamicType_ptr type,  ::DDS::BooleanSeq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::BooleanSeq* get_dynamic_data_adapter_value< ::DDS::BooleanSeq,  ::DDS::BooleanSeq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: BooleanSeq */


/* Begin TYPEDEF: ByteSeq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_ByteSeq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_ByteSeq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_ByteSeq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::ByteSeq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::ByteSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::ByteSeq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::ByteSeq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::ByteSeq,  ::DDS::ByteSeq>(DDS::DynamicType_ptr type, const  ::DDS::ByteSeq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::ByteSeq,  ::DDS::ByteSeq>(DDS::DynamicType_ptr type,  ::DDS::ByteSeq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::ByteSeq* get_dynamic_data_adapter_value< ::DDS::ByteSeq,  ::DDS::ByteSeq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: ByteSeq */


/* Begin TYPEDEF: WstringSeq */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DDS_WstringSeq_xtag {};
template<> OpenDDS_Dcps_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DDS_WstringSeq_xtag>();

template<> OpenDDS_Dcps_Export
const XTypes::TypeMap& getMinimalTypeMap<DDS_WstringSeq_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::DDS::WstringSeq& seq);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const  ::DDS::WstringSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm,  ::DDS::WstringSeq& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
bool gen_skip_over(Serializer& strm,  ::DDS::WstringSeq*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::WstringSeq,  ::DDS::WstringSeq>(DDS::DynamicType_ptr type, const  ::DDS::WstringSeq& value);

template <>
OpenDDS_Dcps_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::DDS::WstringSeq,  ::DDS::WstringSeq>(DDS::DynamicType_ptr type,  ::DDS::WstringSeq& value);

template <>
OpenDDS_Dcps_Export const  ::DDS::WstringSeq* get_dynamic_data_adapter_value< ::DDS::WstringSeq,  ::DDS::WstringSeq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: WstringSeq */

/* End MODULE: DDS */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_DDSDYNAMICDATASEQTYPESUPPORTIMPL_H_F0PMES */
