// TestControl.idl
@topic
struct TestControl
{
    @key long test_id;            // groups messages for a given test run
    boolean start;                // true = start (or update), false = stop
    long expected_entities;       // messages per 10ms cycle
    boolean loan;                 // wether to use loanable in send and recv
    long reserve1;                // spare (for future use)
    long reserve2;                // spare
};
