// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ci.cpp:35

// *************************************************************
// Inline operations for union OpenDDS::Monitor::ValueUnion
// *************************************************************
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ci.cpp:54

ACE_INLINE
void
OpenDDS::Monitor::ValueUnion::_default ()
{
  this->_reset ();
  this->disc_ = static_cast <OpenDDS::Monitor::ValueEnumType> (-1);
}

// Accessor to set the discriminant.
ACE_INLINE
void
OpenDDS::Monitor::ValueUnion::_d (OpenDDS::Monitor::ValueEnumType discval)
{
  this->disc_ = discval;
}

// Accessor to get the discriminant.
ACE_INLINE
OpenDDS::Monitor::ValueEnumType
OpenDDS::Monitor::ValueUnion::_d (void) const
{
  return this->disc_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:571

// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::ValueUnion::integer_value (CORBA::Long val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::INTEGER_TYPE;
  // Set the value.
  this->u_.integer_value_ = val;
}

/// Retrieve the member.
ACE_INLINE
::CORBA::Long
OpenDDS::Monitor::ValueUnion::integer_value (void) const
{
  return this->u_.integer_value_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:571

// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::ValueUnion::double_value (CORBA::Double val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::DOUBLE_TYPE;
  // Set the value.
  this->u_.double_value_ = val;
}

/// Retrieve the member.
ACE_INLINE
::CORBA::Double
OpenDDS::Monitor::ValueUnion::double_value (void) const
{
  return this->u_.double_value_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:866

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::ValueUnion::string_value (char *val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::STRING_TYPE;
  this->u_.string_value_ = val;
}

// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::ValueUnion::string_value (const char *val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::STRING_TYPE;
  // Set the value.
  this->u_.string_value_ = ::CORBA::string_dup (val);
}

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::ValueUnion::string_value (const ::CORBA::String_var &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::STRING_TYPE;
  // Set the value.
  ::CORBA::String_var string_value_var = val;
  this->u_.string_value_ = string_value_var._retn ();
}

ACE_INLINE
const char *
OpenDDS::Monitor::ValueUnion::string_value (void) const // get method
{
  return this->u_.string_value_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::ValueUnion::stat_value (const OpenDDS::Monitor::Statistics &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::STATISTICS_TYPE;
  this->u_.stat_value_ = val;
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::Statistics &
OpenDDS::Monitor::ValueUnion::stat_value (void) const
{
  return this->u_.stat_value_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::Statistics &
OpenDDS::Monitor::ValueUnion::stat_value (void)
{
  return this->u_.stat_value_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:793

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::ValueUnion::string_seq_value (const DDS::StringSeq &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::STRING_LIST_TYPE;
  ACE_NEW (
      this->u_.string_seq_value_,
      DDS::StringSeq (val)
    );
}

/// Readonly get method.
ACE_INLINE
const DDS::StringSeq &
OpenDDS::Monitor::ValueUnion::string_seq_value (void) const
{
  return *this->u_.string_seq_value_;
}

/// Read/write get method.
ACE_INLINE
DDS::StringSeq &
OpenDDS::Monitor::ValueUnion::string_seq_value (void)
{
  return *this->u_.string_seq_value_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ci.cpp:35

// *************************************************************
// Inline operations for union OpenDDS::Monitor::GenericReport
// *************************************************************
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ci.cpp:54

ACE_INLINE
void
OpenDDS::Monitor::GenericReport::_default ()
{
  this->_reset ();
  this->disc_ = static_cast <OpenDDS::Monitor::ReportType> (-1);
}

// Accessor to set the discriminant.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::_d (OpenDDS::Monitor::ReportType discval)
{
  this->disc_ = discval;
}

// Accessor to get the discriminant.
ACE_INLINE
OpenDDS::Monitor::ReportType
OpenDDS::Monitor::GenericReport::_d (void) const
{
  return this->disc_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::sp_report (const OpenDDS::Monitor::ServiceParticipantReport &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::SERVICE_PARTICIPANT_REPORT_TYPE;
  ACE_NEW (
      this->u_.sp_report_,
      OpenDDS::Monitor::ServiceParticipantReport (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::ServiceParticipantReport &
OpenDDS::Monitor::GenericReport::sp_report (void) const
{
  return *this->u_.sp_report_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::ServiceParticipantReport &
OpenDDS::Monitor::GenericReport::sp_report (void)
{
  return *this->u_.sp_report_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::dp_report (const OpenDDS::Monitor::DomainParticipantReport &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::DOMAIN_PARTICIPANT_REPORT_TYPE;
  ACE_NEW (
      this->u_.dp_report_,
      OpenDDS::Monitor::DomainParticipantReport (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::DomainParticipantReport &
OpenDDS::Monitor::GenericReport::dp_report (void) const
{
  return *this->u_.dp_report_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::DomainParticipantReport &
OpenDDS::Monitor::GenericReport::dp_report (void)
{
  return *this->u_.dp_report_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::topic_report (const OpenDDS::Monitor::TopicReport &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::TOPIC_REPORT_TYPE;
  ACE_NEW (
      this->u_.topic_report_,
      OpenDDS::Monitor::TopicReport (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::TopicReport &
OpenDDS::Monitor::GenericReport::topic_report (void) const
{
  return *this->u_.topic_report_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::TopicReport &
OpenDDS::Monitor::GenericReport::topic_report (void)
{
  return *this->u_.topic_report_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::publisher_report (const OpenDDS::Monitor::PublisherReport &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::PUBLISHER_REPORT_TYPE;
  ACE_NEW (
      this->u_.publisher_report_,
      OpenDDS::Monitor::PublisherReport (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::PublisherReport &
OpenDDS::Monitor::GenericReport::publisher_report (void) const
{
  return *this->u_.publisher_report_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::PublisherReport &
OpenDDS::Monitor::GenericReport::publisher_report (void)
{
  return *this->u_.publisher_report_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::subscriber_report (const OpenDDS::Monitor::SubscriberReport &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::SUBSCRIBER_REPORT_TYPE;
  ACE_NEW (
      this->u_.subscriber_report_,
      OpenDDS::Monitor::SubscriberReport (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::SubscriberReport &
OpenDDS::Monitor::GenericReport::subscriber_report (void) const
{
  return *this->u_.subscriber_report_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::SubscriberReport &
OpenDDS::Monitor::GenericReport::subscriber_report (void)
{
  return *this->u_.subscriber_report_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::dw_report (const OpenDDS::Monitor::DataWriterReport &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::DATA_WRITER_REPORT_TYPE;
  ACE_NEW (
      this->u_.dw_report_,
      OpenDDS::Monitor::DataWriterReport (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::DataWriterReport &
OpenDDS::Monitor::GenericReport::dw_report (void) const
{
  return *this->u_.dw_report_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::DataWriterReport &
OpenDDS::Monitor::GenericReport::dw_report (void)
{
  return *this->u_.dw_report_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::dw_per_report (const OpenDDS::Monitor::DataWriterPeriodicReport &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::DATA_WRITER_PERIODIC_REPORT_TYPE;
  ACE_NEW (
      this->u_.dw_per_report_,
      OpenDDS::Monitor::DataWriterPeriodicReport (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::DataWriterPeriodicReport &
OpenDDS::Monitor::GenericReport::dw_per_report (void) const
{
  return *this->u_.dw_per_report_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::DataWriterPeriodicReport &
OpenDDS::Monitor::GenericReport::dw_per_report (void)
{
  return *this->u_.dw_per_report_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::dr_report (const OpenDDS::Monitor::DataReaderReport &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::DATA_READER_REPORT_TYPE;
  ACE_NEW (
      this->u_.dr_report_,
      OpenDDS::Monitor::DataReaderReport (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::DataReaderReport &
OpenDDS::Monitor::GenericReport::dr_report (void) const
{
  return *this->u_.dr_report_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::DataReaderReport &
OpenDDS::Monitor::GenericReport::dr_report (void)
{
  return *this->u_.dr_report_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::dr_per_report (const OpenDDS::Monitor::DataReaderPeriodicReport &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::DATA_READER_PERIODIC_REPORT_TYPE;
  ACE_NEW (
      this->u_.dr_per_report_,
      OpenDDS::Monitor::DataReaderPeriodicReport (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::DataReaderPeriodicReport &
OpenDDS::Monitor::GenericReport::dr_per_report (void) const
{
  return *this->u_.dr_per_report_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::DataReaderPeriodicReport &
OpenDDS::Monitor::GenericReport::dr_per_report (void)
{
  return *this->u_.dr_per_report_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::Monitor::GenericReport::transport_report (const OpenDDS::Monitor::TransportReport &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = OpenDDS::Monitor::TRANSPORT_REPORT_TYPE;
  ACE_NEW (
      this->u_.transport_report_,
      OpenDDS::Monitor::TransportReport (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::Monitor::TransportReport &
OpenDDS::Monitor::GenericReport::transport_report (void) const
{
  return *this->u_.transport_report_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::Monitor::TransportReport &
OpenDDS::Monitor::GenericReport::transport_report (void)
{
  return *this->u_.transport_report_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ci.cpp:58



ACE_INLINE
OpenDDS::Monitor::ProcessMonitor::ProcessMonitor (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (objref, _tao_collocated, servant, oc)
{
}

ACE_INLINE
OpenDDS::Monitor::ProcessMonitor::ProcessMonitor (
    ::IOP::IOR *ior,
    TAO_ORB_Core *oc)
  : ::CORBA::Object (ior, oc)
{
}


OPENDDS_END_VERSIONED_NAMESPACE_DECL


