// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_MONITORC_P0PPHP_H_
#define _TAO_IDL_MONITORC_P0PPHP_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "monitor_export.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"
#include /**/ "dds/Versioned_Namespace.h"

#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsGuidC.h"
#include "tao/ULongSeqC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 23
#error This file should be regenerated with TAO_IDL
#endif

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



OPENDDS_END_VERSIONED_NAMESPACE_DECL



OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_root/root_ch.cpp:155



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace OpenDDS
{
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

  namespace Monitor
  {
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const CORBA::Long MONITOR_DOMAIN_ID = -999;
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const CORBA::Long MONITOR_TRANSPORT_ID = 999;
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const char *const SERVICE_PARTICIPANT_MONITOR_TOPIC = "Service Participant Monitor";
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const char *const DOMAIN_PARTICIPANT_MONITOR_TOPIC = "Domain Participant Monitor";
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const char *const TOPIC_MONITOR_TOPIC = "Topic Monitor";
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const char *const PUBLISHER_MONITOR_TOPIC = "Publisher Monitor";
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const char *const SUBSCRIBER_MONITOR_TOPIC = "Subscriber Monitor";
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const char *const DATA_WRITER_MONITOR_TOPIC = "Data Writer Monitor";
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const char *const DATA_WRITER_PERIODIC_MONITOR_TOPIC = "Data Writer Periodic Monitor";
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const char *const DATA_READER_MONITOR_TOPIC = "Data Reader Monitor";
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const char *const DATA_READER_PERIODIC_MONITOR_TOPIC = "Data Reader Periodic Monitor";
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const char *const TRANSPORT_MONITOR_TOPIC = "Transport Monitor";
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct Statistics;

    typedef
      ::TAO_Fixed_Var_T<
          Statistics
        >
      Statistics_var;

    typedef
      Statistics &
      Statistics_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export Statistics
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef Statistics_var _var_type;
      typedef Statistics_out _out_type;
      
      ::CORBA::ULong n;
      ::CORBA::Double maximum;
      ::CORBA::Double minimum;
      ::CORBA::Double mean;
      ::CORBA::Double variance;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/enum_ch.cpp:43

    enum ValueEnumType
    {
      INTEGER_TYPE,
      DOUBLE_TYPE,
      STRING_TYPE,
      STATISTICS_TYPE,
      STRING_LIST_TYPE
    };

    typedef ValueEnumType &ValueEnumType_out;
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    class ValueUnion;

    typedef
      ::TAO_Var_Var_T<
          ValueUnion
        >
      ValueUnion_var;

    typedef
      ::TAO_Out_T<
          ValueUnion
        >
      ValueUnion_out;

    class OpenDDS_monitor_Export ValueUnion
    {
    public:
      ValueUnion (void);
      ValueUnion (const ValueUnion &);
      ~ValueUnion (void);

      ValueUnion &operator= (const ValueUnion &);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ch.cpp:66

      

      void _d (OpenDDS::Monitor::ValueEnumType);
      OpenDDS::Monitor::ValueEnumType _d (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef ValueUnion_var _var_type;
      typedef ValueUnion_out _out_type;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:440

      

      void integer_value ( ::CORBA::Long);
      ::CORBA::Long integer_value (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:440

      

      void double_value ( ::CORBA::Double);
      ::CORBA::Double double_value (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:606

      

      void string_value (char *);
      void string_value (const char *);
      void string_value (const ::CORBA::String_var&);
      const char *string_value (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void stat_value (const OpenDDS::Monitor::Statistics &);
      const OpenDDS::Monitor::Statistics &stat_value (void) const;
      OpenDDS::Monitor::Statistics &stat_value (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:575

      

      void string_seq_value (const DDS::StringSeq &);
      const DDS::StringSeq &string_seq_value (void) const;
      DDS::StringSeq &string_seq_value (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ch.cpp:120

      

      void _default (void);
    private:
      OpenDDS::Monitor::ValueEnumType disc_;

      union
      {
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:369

        
        ::CORBA::Long integer_value_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:369

        
        ::CORBA::Double double_value_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:476

        
        char *string_value_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::Statistics stat_value_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:447

        
        DDS::StringSeq *string_seq_value_;
      } u_;

      /// TAO extension - frees any allocated storage.
      void _reset (void);
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct NameValuePair;

    typedef
      ::TAO_Var_Var_T<
          NameValuePair
        >
      NameValuePair_var;

    typedef
      ::TAO_Out_T<
          NameValuePair
        >
      NameValuePair_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export NameValuePair
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef NameValuePair_var _var_type;
      typedef NameValuePair_out _out_type;
      
      ::TAO::String_Manager name;
      

      OpenDDS::Monitor::ValueUnion value;
    };

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

    

#if !defined (_OPENDDS_MONITOR_NVPSEQ_CH_)
#define _OPENDDS_MONITOR_NVPSEQ_CH_

    class NVPSeq;
    typedef ::TAO_VarSeq_Var_T<NVPSeq> NVPSeq_var;
    typedef ::TAO_Seq_Out_T<NVPSeq> NVPSeq_out;
    

    class OpenDDS_monitor_Export NVPSeq
      : public
          ::TAO::unbounded_value_sequence< NameValuePair>
    {
    public:
      NVPSeq (void);
      NVPSeq ( ::CORBA::ULong max);
      NVPSeq (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        NameValuePair* buffer,
        ::CORBA::Boolean release = false);
#if defined (ACE_HAS_CPP11)
      NVPSeq (const NVPSeq &) = default;
      NVPSeq (NVPSeq &&) = default;
      NVPSeq& operator= (const NVPSeq &) = default;
      NVPSeq& operator= (NVPSeq &&) = default;
#endif /* ACE_HAS_CPP11 */
      virtual ~NVPSeq (void);
      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef NVPSeq_var _var_type;
      typedef NVPSeq_out _out_type;
    };

#endif /* end #if !defined */
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct ServiceParticipantReport;

    typedef
      ::TAO_Var_Var_T<
          ServiceParticipantReport
        >
      ServiceParticipantReport_var;

    typedef
      ::TAO_Out_T<
          ServiceParticipantReport
        >
      ServiceParticipantReport_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export ServiceParticipantReport
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef ServiceParticipantReport_var _var_type;
      typedef ServiceParticipantReport_out _out_type;
      
      ::TAO::String_Manager host;
      ::CORBA::Long pid;
      OpenDDS::DCPS::GUIDSeq domain_participants;
      CORBA::ULongSeq transports;
      OpenDDS::Monitor::NVPSeq values;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DomainParticipantReport;

    typedef
      ::TAO_Var_Var_T<
          DomainParticipantReport
        >
      DomainParticipantReport_var;

    typedef
      ::TAO_Out_T<
          DomainParticipantReport
        >
      DomainParticipantReport_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export DomainParticipantReport
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DomainParticipantReport_var _var_type;
      typedef DomainParticipantReport_out _out_type;
      
      ::TAO::String_Manager host;
      ::CORBA::Long pid;
      OpenDDS::DCPS::GUID_t dp_id;
      DDS::DomainId_t domain_id;
      OpenDDS::DCPS::GUIDSeq topics;
      OpenDDS::Monitor::NVPSeq values;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct TopicReport;

    typedef
      ::TAO_Var_Var_T<
          TopicReport
        >
      TopicReport_var;

    typedef
      ::TAO_Out_T<
          TopicReport
        >
      TopicReport_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export TopicReport
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TopicReport_var _var_type;
      typedef TopicReport_out _out_type;
      
      OpenDDS::DCPS::GUID_t dp_id;
      OpenDDS::DCPS::GUID_t topic_id;
      ::TAO::String_Manager topic_name;
      ::TAO::String_Manager type_name;
      OpenDDS::Monitor::NVPSeq values;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct PublisherReport;

    typedef
      ::TAO_Var_Var_T<
          PublisherReport
        >
      PublisherReport_var;

    typedef
      ::TAO_Out_T<
          PublisherReport
        >
      PublisherReport_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export PublisherReport
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef PublisherReport_var _var_type;
      typedef PublisherReport_out _out_type;
      
      DDS::InstanceHandle_t handle;
      OpenDDS::DCPS::GUID_t dp_id;
      ::CORBA::ULong transport_id;
      OpenDDS::DCPS::GUIDSeq writers;
      OpenDDS::Monitor::NVPSeq values;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct SubscriberReport;

    typedef
      ::TAO_Var_Var_T<
          SubscriberReport
        >
      SubscriberReport_var;

    typedef
      ::TAO_Out_T<
          SubscriberReport
        >
      SubscriberReport_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export SubscriberReport
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef SubscriberReport_var _var_type;
      typedef SubscriberReport_out _out_type;
      
      DDS::InstanceHandle_t handle;
      OpenDDS::DCPS::GUID_t dp_id;
      ::CORBA::ULong transport_id;
      OpenDDS::DCPS::GUIDSeq readers;
      OpenDDS::Monitor::NVPSeq values;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DataWriterAssociation;

    typedef
      ::TAO_Fixed_Var_T<
          DataWriterAssociation
        >
      DataWriterAssociation_var;

    typedef
      DataWriterAssociation &
      DataWriterAssociation_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export DataWriterAssociation
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DataWriterAssociation_var _var_type;
      typedef DataWriterAssociation_out _out_type;
      
      OpenDDS::DCPS::GUID_t dr_id;
    };

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

    

#if !defined (_OPENDDS_MONITOR_DWASSOCIATIONS_CH_)
#define _OPENDDS_MONITOR_DWASSOCIATIONS_CH_

    class DWAssociations;
    typedef ::TAO_FixedSeq_Var_T<DWAssociations> DWAssociations_var;
    typedef ::TAO_Seq_Out_T<DWAssociations> DWAssociations_out;
    

    class OpenDDS_monitor_Export DWAssociations
      : public
          ::TAO::unbounded_value_sequence< DataWriterAssociation>
    {
    public:
      DWAssociations (void);
      DWAssociations ( ::CORBA::ULong max);
      DWAssociations (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        DataWriterAssociation* buffer,
        ::CORBA::Boolean release = false);
#if defined (ACE_HAS_CPP11)
      DWAssociations (const DWAssociations &) = default;
      DWAssociations (DWAssociations &&) = default;
      DWAssociations& operator= (const DWAssociations &) = default;
      DWAssociations& operator= (DWAssociations &&) = default;
#endif /* ACE_HAS_CPP11 */
      virtual ~DWAssociations (void);
      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DWAssociations_var _var_type;
      typedef DWAssociations_out _out_type;
    };

#endif /* end #if !defined */
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DataWriterReport;

    typedef
      ::TAO_Var_Var_T<
          DataWriterReport
        >
      DataWriterReport_var;

    typedef
      ::TAO_Out_T<
          DataWriterReport
        >
      DataWriterReport_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export DataWriterReport
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DataWriterReport_var _var_type;
      typedef DataWriterReport_out _out_type;
      
      OpenDDS::DCPS::GUID_t dp_id;
      DDS::InstanceHandle_t pub_handle;
      OpenDDS::DCPS::GUID_t dw_id;
      OpenDDS::DCPS::GUID_t topic_id;
      DDS::InstanceHandleSeq instances;
      OpenDDS::Monitor::DWAssociations associations;
      OpenDDS::Monitor::NVPSeq values;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DataWriterAssociationPeriodic;

    typedef
      ::TAO_Fixed_Var_T<
          DataWriterAssociationPeriodic
        >
      DataWriterAssociationPeriodic_var;

    typedef
      DataWriterAssociationPeriodic &
      DataWriterAssociationPeriodic_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export DataWriterAssociationPeriodic
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DataWriterAssociationPeriodic_var _var_type;
      typedef DataWriterAssociationPeriodic_out _out_type;
      
      OpenDDS::DCPS::GUID_t dr_id;
      ::CORBA::ULong sequence_number;
    };

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

    

#if !defined (_OPENDDS_MONITOR_DWASSOCIATIONSPERIODIC_CH_)
#define _OPENDDS_MONITOR_DWASSOCIATIONSPERIODIC_CH_

    class DWAssociationsPeriodic;
    typedef ::TAO_FixedSeq_Var_T<DWAssociationsPeriodic> DWAssociationsPeriodic_var;
    typedef ::TAO_Seq_Out_T<DWAssociationsPeriodic> DWAssociationsPeriodic_out;
    

    class OpenDDS_monitor_Export DWAssociationsPeriodic
      : public
          ::TAO::unbounded_value_sequence< DataWriterAssociationPeriodic>
    {
    public:
      DWAssociationsPeriodic (void);
      DWAssociationsPeriodic ( ::CORBA::ULong max);
      DWAssociationsPeriodic (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        DataWriterAssociationPeriodic* buffer,
        ::CORBA::Boolean release = false);
#if defined (ACE_HAS_CPP11)
      DWAssociationsPeriodic (const DWAssociationsPeriodic &) = default;
      DWAssociationsPeriodic (DWAssociationsPeriodic &&) = default;
      DWAssociationsPeriodic& operator= (const DWAssociationsPeriodic &) = default;
      DWAssociationsPeriodic& operator= (DWAssociationsPeriodic &&) = default;
#endif /* ACE_HAS_CPP11 */
      virtual ~DWAssociationsPeriodic (void);
      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DWAssociationsPeriodic_var _var_type;
      typedef DWAssociationsPeriodic_out _out_type;
    };

#endif /* end #if !defined */
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DataWriterPeriodicReport;

    typedef
      ::TAO_Var_Var_T<
          DataWriterPeriodicReport
        >
      DataWriterPeriodicReport_var;

    typedef
      ::TAO_Out_T<
          DataWriterPeriodicReport
        >
      DataWriterPeriodicReport_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export DataWriterPeriodicReport
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DataWriterPeriodicReport_var _var_type;
      typedef DataWriterPeriodicReport_out _out_type;
      
      OpenDDS::DCPS::GUID_t dw_id;
      ::CORBA::ULong data_dropped_count;
      ::CORBA::ULong data_delivered_count;
      ::CORBA::ULong control_dropped_count;
      ::CORBA::ULong control_delivered_count;
      OpenDDS::Monitor::DWAssociationsPeriodic associations;
      OpenDDS::Monitor::NVPSeq values;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DataReaderAssociation;

    typedef
      ::TAO_Fixed_Var_T<
          DataReaderAssociation
        >
      DataReaderAssociation_var;

    typedef
      DataReaderAssociation &
      DataReaderAssociation_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export DataReaderAssociation
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DataReaderAssociation_var _var_type;
      typedef DataReaderAssociation_out _out_type;
      
      OpenDDS::DCPS::GUID_t dw_id;
      ::CORBA::Short state;
    };

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

    

#if !defined (_OPENDDS_MONITOR_DRASSOCIATIONS_CH_)
#define _OPENDDS_MONITOR_DRASSOCIATIONS_CH_

    class DRAssociations;
    typedef ::TAO_FixedSeq_Var_T<DRAssociations> DRAssociations_var;
    typedef ::TAO_Seq_Out_T<DRAssociations> DRAssociations_out;
    

    class OpenDDS_monitor_Export DRAssociations
      : public
          ::TAO::unbounded_value_sequence< DataReaderAssociation>
    {
    public:
      DRAssociations (void);
      DRAssociations ( ::CORBA::ULong max);
      DRAssociations (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        DataReaderAssociation* buffer,
        ::CORBA::Boolean release = false);
#if defined (ACE_HAS_CPP11)
      DRAssociations (const DRAssociations &) = default;
      DRAssociations (DRAssociations &&) = default;
      DRAssociations& operator= (const DRAssociations &) = default;
      DRAssociations& operator= (DRAssociations &&) = default;
#endif /* ACE_HAS_CPP11 */
      virtual ~DRAssociations (void);
      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DRAssociations_var _var_type;
      typedef DRAssociations_out _out_type;
    };

#endif /* end #if !defined */
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DataReaderReport;

    typedef
      ::TAO_Var_Var_T<
          DataReaderReport
        >
      DataReaderReport_var;

    typedef
      ::TAO_Out_T<
          DataReaderReport
        >
      DataReaderReport_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export DataReaderReport
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DataReaderReport_var _var_type;
      typedef DataReaderReport_out _out_type;
      
      OpenDDS::DCPS::GUID_t dp_id;
      DDS::InstanceHandle_t sub_handle;
      OpenDDS::DCPS::GUID_t dr_id;
      OpenDDS::DCPS::GUID_t topic_id;
      DDS::InstanceHandleSeq instances;
      OpenDDS::Monitor::DRAssociations associations;
      OpenDDS::Monitor::NVPSeq values;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DataReaderAssociationPeriodic;

    typedef
      ::TAO_Fixed_Var_T<
          DataReaderAssociationPeriodic
        >
      DataReaderAssociationPeriodic_var;

    typedef
      DataReaderAssociationPeriodic &
      DataReaderAssociationPeriodic_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export DataReaderAssociationPeriodic
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DataReaderAssociationPeriodic_var _var_type;
      typedef DataReaderAssociationPeriodic_out _out_type;
      
      OpenDDS::DCPS::GUID_t dw_id;
      ::CORBA::ULong samples_available;
    };

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

    

#if !defined (_OPENDDS_MONITOR_DRASSOCIATIONSPERIODIC_CH_)
#define _OPENDDS_MONITOR_DRASSOCIATIONSPERIODIC_CH_

    class DRAssociationsPeriodic;
    typedef ::TAO_FixedSeq_Var_T<DRAssociationsPeriodic> DRAssociationsPeriodic_var;
    typedef ::TAO_Seq_Out_T<DRAssociationsPeriodic> DRAssociationsPeriodic_out;
    

    class OpenDDS_monitor_Export DRAssociationsPeriodic
      : public
          ::TAO::unbounded_value_sequence< DataReaderAssociationPeriodic>
    {
    public:
      DRAssociationsPeriodic (void);
      DRAssociationsPeriodic ( ::CORBA::ULong max);
      DRAssociationsPeriodic (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        DataReaderAssociationPeriodic* buffer,
        ::CORBA::Boolean release = false);
#if defined (ACE_HAS_CPP11)
      DRAssociationsPeriodic (const DRAssociationsPeriodic &) = default;
      DRAssociationsPeriodic (DRAssociationsPeriodic &&) = default;
      DRAssociationsPeriodic& operator= (const DRAssociationsPeriodic &) = default;
      DRAssociationsPeriodic& operator= (DRAssociationsPeriodic &&) = default;
#endif /* ACE_HAS_CPP11 */
      virtual ~DRAssociationsPeriodic (void);
      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DRAssociationsPeriodic_var _var_type;
      typedef DRAssociationsPeriodic_out _out_type;
    };

#endif /* end #if !defined */
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct DataReaderPeriodicReport;

    typedef
      ::TAO_Var_Var_T<
          DataReaderPeriodicReport
        >
      DataReaderPeriodicReport_var;

    typedef
      ::TAO_Out_T<
          DataReaderPeriodicReport
        >
      DataReaderPeriodicReport_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export DataReaderPeriodicReport
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef DataReaderPeriodicReport_var _var_type;
      typedef DataReaderPeriodicReport_out _out_type;
      
      OpenDDS::DCPS::GUID_t dr_id;
      OpenDDS::Monitor::DRAssociationsPeriodic associations;
      OpenDDS::Monitor::NVPSeq values;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct TransportReport;

    typedef
      ::TAO_Var_Var_T<
          TransportReport
        >
      TransportReport_var;

    typedef
      ::TAO_Out_T<
          TransportReport
        >
      TransportReport_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_monitor_Export TransportReport
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TransportReport_var _var_type;
      typedef TransportReport_out _out_type;
      
      ::TAO::String_Manager host;
      ::CORBA::Long pid;
      ::CORBA::ULong transport_id;
      ::TAO::String_Manager transport_type;
      OpenDDS::Monitor::NVPSeq values;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/enum_ch.cpp:43

    enum ReportType
    {
      SERVICE_PARTICIPANT_REPORT_TYPE,
      DOMAIN_PARTICIPANT_REPORT_TYPE,
      TOPIC_REPORT_TYPE,
      PUBLISHER_REPORT_TYPE,
      SUBSCRIBER_REPORT_TYPE,
      DATA_WRITER_REPORT_TYPE,
      DATA_WRITER_PERIODIC_REPORT_TYPE,
      DATA_READER_REPORT_TYPE,
      DATA_READER_PERIODIC_REPORT_TYPE,
      TRANSPORT_REPORT_TYPE
    };

    typedef ReportType &ReportType_out;
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    class GenericReport;

    typedef
      ::TAO_Var_Var_T<
          GenericReport
        >
      GenericReport_var;

    typedef
      ::TAO_Out_T<
          GenericReport
        >
      GenericReport_out;

    class OpenDDS_monitor_Export GenericReport
    {
    public:
      GenericReport (void);
      GenericReport (const GenericReport &);
      ~GenericReport (void);

      GenericReport &operator= (const GenericReport &);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ch.cpp:66

      

      void _d (OpenDDS::Monitor::ReportType);
      OpenDDS::Monitor::ReportType _d (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef GenericReport_var _var_type;
      typedef GenericReport_out _out_type;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void sp_report (const OpenDDS::Monitor::ServiceParticipantReport &);
      const OpenDDS::Monitor::ServiceParticipantReport &sp_report (void) const;
      OpenDDS::Monitor::ServiceParticipantReport &sp_report (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void dp_report (const OpenDDS::Monitor::DomainParticipantReport &);
      const OpenDDS::Monitor::DomainParticipantReport &dp_report (void) const;
      OpenDDS::Monitor::DomainParticipantReport &dp_report (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void topic_report (const OpenDDS::Monitor::TopicReport &);
      const OpenDDS::Monitor::TopicReport &topic_report (void) const;
      OpenDDS::Monitor::TopicReport &topic_report (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void publisher_report (const OpenDDS::Monitor::PublisherReport &);
      const OpenDDS::Monitor::PublisherReport &publisher_report (void) const;
      OpenDDS::Monitor::PublisherReport &publisher_report (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void subscriber_report (const OpenDDS::Monitor::SubscriberReport &);
      const OpenDDS::Monitor::SubscriberReport &subscriber_report (void) const;
      OpenDDS::Monitor::SubscriberReport &subscriber_report (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void dw_report (const OpenDDS::Monitor::DataWriterReport &);
      const OpenDDS::Monitor::DataWriterReport &dw_report (void) const;
      OpenDDS::Monitor::DataWriterReport &dw_report (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void dw_per_report (const OpenDDS::Monitor::DataWriterPeriodicReport &);
      const OpenDDS::Monitor::DataWriterPeriodicReport &dw_per_report (void) const;
      OpenDDS::Monitor::DataWriterPeriodicReport &dw_per_report (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void dr_report (const OpenDDS::Monitor::DataReaderReport &);
      const OpenDDS::Monitor::DataReaderReport &dr_report (void) const;
      OpenDDS::Monitor::DataReaderReport &dr_report (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void dr_per_report (const OpenDDS::Monitor::DataReaderPeriodicReport &);
      const OpenDDS::Monitor::DataReaderPeriodicReport &dr_per_report (void) const;
      OpenDDS::Monitor::DataReaderPeriodicReport &dr_per_report (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void transport_report (const OpenDDS::Monitor::TransportReport &);
      const OpenDDS::Monitor::TransportReport &transport_report (void) const;
      OpenDDS::Monitor::TransportReport &transport_report (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ch.cpp:120

      

      void _default (void);
    private:
      OpenDDS::Monitor::ReportType disc_;

      union
      {
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::ServiceParticipantReport *sp_report_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::DomainParticipantReport *dp_report_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::TopicReport *topic_report_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::PublisherReport *publisher_report_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::SubscriberReport *subscriber_report_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::DataWriterReport *dw_report_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::DataWriterPeriodicReport *dw_per_report_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::DataReaderReport *dr_report_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::DataReaderPeriodicReport *dr_per_report_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::Monitor::TransportReport *transport_report_;
      } u_;

      /// TAO extension - frees any allocated storage.
      void _reset (void);
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

    

#if !defined (_OPENDDS_MONITOR_PROCESSMONITOR__VAR_OUT_CH_)
#define _OPENDDS_MONITOR_PROCESSMONITOR__VAR_OUT_CH_

    class ProcessMonitor;
    typedef ProcessMonitor *ProcessMonitor_ptr;
    typedef TAO_Objref_Var_T<ProcessMonitor> ProcessMonitor_var;
    typedef TAO_Objref_Out_T<ProcessMonitor> ProcessMonitor_out;
    

#endif /* end #if !defined */

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

    

    class OpenDDS_monitor_Export ProcessMonitor
      : public virtual ::CORBA::Object
    {
    public:
      friend class TAO::Narrow_Utils<ProcessMonitor>;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      typedef ProcessMonitor_ptr _ptr_type;
      typedef ProcessMonitor_var _var_type;
      typedef ProcessMonitor_out _out_type;

      // The static operations.
      static ProcessMonitor_ptr _duplicate (ProcessMonitor_ptr obj);

      static void _tao_release (ProcessMonitor_ptr obj);

      static ProcessMonitor_ptr _narrow (::CORBA::Object_ptr obj);
      static ProcessMonitor_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
      static ProcessMonitor_ptr _nil (void);

      virtual ::OpenDDS::Monitor::GenericReport * retrieve_report (
        const char * name);

      virtual void enable_report_collection (
        void);

      virtual void disable_report_collection (
        void);

      virtual void enable_report_publishing (
        void);

      virtual void diable_report_publishing (
        void);

      virtual void set_publishing_period (
        const ::DDS::Duration_t & period);

      virtual ::DDS::Duration_t get_publishing_period (
        void);

      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

      

      virtual ::CORBA::Boolean _is_a (const char *type_id);
      virtual const char* _interface_repository_id (void) const;
      virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
    
    protected:
      // Concrete interface only.
      ProcessMonitor (void);

      // Concrete non-local interface only.
      ProcessMonitor (
          ::IOP::IOR *ior,
          TAO_ORB_Core *orb_core);
      
      // Non-local interface only.
      ProcessMonitor (
          TAO_Stub *objref,
          ::CORBA::Boolean _tao_collocated = false,
          TAO_Abstract_ServantBase *servant = 0,
          TAO_ORB_Core *orb_core = 0);

      virtual ~ProcessMonitor (void);
    
    private:
      // Private and unimplemented for concrete interfaces.
      ACE_UNIMPLEMENTED_FUNC (ProcessMonitor (const ProcessMonitor &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (ProcessMonitor (ProcessMonitor &&))
#endif /* ACE_HAS_CPP11 */
      ACE_UNIMPLEMENTED_FUNC (ProcessMonitor &operator= (const ProcessMonitor &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (ProcessMonitor &operator= (ProcessMonitor &&))
#endif /* ACE_HAS_CPP11 */
    };
  
  
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62

  
  } // module OpenDDS::Monitor


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module OpenDDS
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::Statistics>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::Statistics,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:890

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::ValueEnumType>
    : public
        Basic_Arg_Traits_T<
            ::OpenDDS::Monitor::ValueEnumType,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::ValueUnion>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::ValueUnion,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::NameValuePair>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::NameValuePair,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::NVPSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::NVPSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::ServiceParticipantReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::ServiceParticipantReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DomainParticipantReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DomainParticipantReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::TopicReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::TopicReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::PublisherReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::PublisherReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::SubscriberReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::SubscriberReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DataWriterAssociation>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DataWriterAssociation,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DWAssociations>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DWAssociations,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DataWriterReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DataWriterReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DataWriterAssociationPeriodic>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DataWriterAssociationPeriodic,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DWAssociationsPeriodic>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DWAssociationsPeriodic,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DataWriterPeriodicReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DataWriterPeriodicReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DataReaderAssociation>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DataReaderAssociation,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DRAssociations>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DRAssociations,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DataReaderReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DataReaderReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DataReaderAssociationPeriodic>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DataReaderAssociationPeriodic,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DRAssociationsPeriodic>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DRAssociationsPeriodic,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::DataReaderPeriodicReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::DataReaderPeriodicReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::TransportReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::TransportReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:890

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::ReportType>
    : public
        Basic_Arg_Traits_T<
            ::OpenDDS::Monitor::ReportType,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class Arg_Traits< ::OpenDDS::Monitor::GenericReport>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::Monitor::GenericReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:142

  

#if !defined (_OPENDDS_MONITOR_PROCESSMONITOR__ARG_TRAITS_)
#define _OPENDDS_MONITOR_PROCESSMONITOR__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::OpenDDS::Monitor::ProcessMonitor>
    : public
        Object_Arg_Traits_T<
            ::OpenDDS::Monitor::ProcessMonitor_ptr,
            ::OpenDDS::Monitor::ProcessMonitor_var,
            ::OpenDDS::Monitor::ProcessMonitor_out,
            TAO::Objref_Traits<OpenDDS::Monitor::ProcessMonitor>,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_OPENDDS_MONITOR_PROCESSMONITOR__TRAITS_)
#define _OPENDDS_MONITOR_PROCESSMONITOR__TRAITS_

  template<>
  struct OpenDDS_monitor_Export Objref_Traits< ::OpenDDS::Monitor::ProcessMonitor>
  {
    static ::OpenDDS::Monitor::ProcessMonitor_ptr duplicate (
        ::OpenDDS::Monitor::ProcessMonitor_ptr p);
    static void release (
        ::OpenDDS::Monitor::ProcessMonitor_ptr p);
    static ::OpenDDS::Monitor::ProcessMonitor_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::OpenDDS::Monitor::ProcessMonitor_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::Statistics &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::Statistics &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/cdr_op_ch.cpp:33



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, OpenDDS::Monitor::ValueEnumType _tao_enumerator);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &strm, OpenDDS::Monitor::ValueEnumType &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/cdr_op_ch.cpp:37



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::ValueUnion &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::ValueUnion &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::NameValuePair &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::NameValuePair &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_OpenDDS_Monitor_NVPSeq_H_
#define _TAO_CDR_OP_OpenDDS_Monitor_NVPSeq_H_

OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_monitor_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::Monitor::NVPSeq &_tao_sequence);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::Monitor::NVPSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




#endif /* _TAO_CDR_OP_OpenDDS_Monitor_NVPSeq_H_ */
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::ServiceParticipantReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::ServiceParticipantReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::DomainParticipantReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::DomainParticipantReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::TopicReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::TopicReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::PublisherReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::PublisherReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::SubscriberReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::SubscriberReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::DataWriterAssociation &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::DataWriterAssociation &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_OpenDDS_Monitor_DWAssociations_H_
#define _TAO_CDR_OP_OpenDDS_Monitor_DWAssociations_H_

OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_monitor_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::Monitor::DWAssociations &_tao_sequence);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::Monitor::DWAssociations &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




#endif /* _TAO_CDR_OP_OpenDDS_Monitor_DWAssociations_H_ */
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::DataWriterReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::DataWriterReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::DataWriterAssociationPeriodic &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::DataWriterAssociationPeriodic &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_OpenDDS_Monitor_DWAssociationsPeriodic_H_
#define _TAO_CDR_OP_OpenDDS_Monitor_DWAssociationsPeriodic_H_

OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_monitor_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::Monitor::DWAssociationsPeriodic &_tao_sequence);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::Monitor::DWAssociationsPeriodic &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




#endif /* _TAO_CDR_OP_OpenDDS_Monitor_DWAssociationsPeriodic_H_ */
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::DataWriterPeriodicReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::DataWriterPeriodicReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::DataReaderAssociation &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::DataReaderAssociation &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_OpenDDS_Monitor_DRAssociations_H_
#define _TAO_CDR_OP_OpenDDS_Monitor_DRAssociations_H_

OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_monitor_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::Monitor::DRAssociations &_tao_sequence);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::Monitor::DRAssociations &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




#endif /* _TAO_CDR_OP_OpenDDS_Monitor_DRAssociations_H_ */
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::DataReaderReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::DataReaderReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::DataReaderAssociationPeriodic &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::DataReaderAssociationPeriodic &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_OpenDDS_Monitor_DRAssociationsPeriodic_H_
#define _TAO_CDR_OP_OpenDDS_Monitor_DRAssociationsPeriodic_H_

OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_monitor_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::Monitor::DRAssociationsPeriodic &_tao_sequence);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::Monitor::DRAssociationsPeriodic &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




#endif /* _TAO_CDR_OP_OpenDDS_Monitor_DRAssociationsPeriodic_H_ */
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::DataReaderPeriodicReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::DataReaderPeriodicReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:42



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::TransportReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::TransportReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/cdr_op_ch.cpp:33



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, OpenDDS::Monitor::ReportType _tao_enumerator);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &strm, OpenDDS::Monitor::ReportType &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/cdr_op_ch.cpp:37



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::GenericReport &);
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::GenericReport &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL





// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_ch.cpp:40




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_monitor_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::Monitor::ProcessMonitor_ptr );
OpenDDS_monitor_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::Monitor::ProcessMonitor_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1649



OPENDDS_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "monitorC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

