// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:454

#ifndef _TAO_IDL_MONITORS_XH0P00_H_
#define _TAO_IDL_MONITORS_XH0P00_H_

#include /**/ "ace/pre.h"

#include "monitorC.h"
#include "dds/DdsDcpsInfrastructureS.h"
#include "dds/DdsDcpsGuidS.h"
#include "tao/ULongSeqS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::Statistics>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::Statistics,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:890

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::ValueEnumType>
    : public
        Basic_SArg_Traits_T<
            ::OpenDDS::Monitor::ValueEnumType,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::ValueUnion>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::ValueUnion,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::NameValuePair>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::NameValuePair,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::NVPSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::NVPSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::ServiceParticipantReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::ServiceParticipantReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DomainParticipantReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DomainParticipantReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::TopicReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::TopicReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::PublisherReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::PublisherReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::SubscriberReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::SubscriberReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DataWriterAssociation>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DataWriterAssociation,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DWAssociations>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DWAssociations,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DataWriterReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DataWriterReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DataWriterAssociationPeriodic>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DataWriterAssociationPeriodic,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DWAssociationsPeriodic>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DWAssociationsPeriodic,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DataWriterPeriodicReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DataWriterPeriodicReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DataReaderAssociation>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DataReaderAssociation,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DRAssociations>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DRAssociations,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DataReaderReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DataReaderReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DataReaderAssociationPeriodic>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DataReaderAssociationPeriodic,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DRAssociationsPeriodic>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DRAssociationsPeriodic,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::DataReaderPeriodicReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::DataReaderPeriodicReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::TransportReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::TransportReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:890

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::ReportType>
    : public
        Basic_SArg_Traits_T<
            ::OpenDDS::Monitor::ReportType,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class SArg_Traits< ::OpenDDS::Monitor::GenericReport>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Monitor::GenericReport,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:142

  

#if !defined (_OPENDDS_MONITOR_PROCESSMONITOR__SARG_TRAITS_)
#define _OPENDDS_MONITOR_PROCESSMONITOR__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::OpenDDS::Monitor::ProcessMonitor>
    : public
        Object_SArg_Traits_T<
            ::OpenDDS::Monitor::ProcessMonitor_ptr,
            ::OpenDDS::Monitor::ProcessMonitor_var,
            ::OpenDDS::Monitor::ProcessMonitor_out,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:34

namespace POA_OpenDDS
{
  
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:34

  namespace Monitor
  {
    

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp:72

    

    class ProcessMonitor;
    typedef ProcessMonitor *ProcessMonitor_ptr;

    class OpenDDS_monitor_Export ProcessMonitor
      : public virtual PortableServer::ServantBase
    {
    protected:
      ProcessMonitor (void);
    
    public:
      /// Useful for template programming.
      typedef ::OpenDDS::Monitor::ProcessMonitor _stub_type;
      typedef ::OpenDDS::Monitor::ProcessMonitor_ptr _stub_ptr_type;
      typedef ::OpenDDS::Monitor::ProcessMonitor_var _stub_var_type;

      ProcessMonitor (const ProcessMonitor& rhs)
#ifdef ACE_HAS_CPP11
        = default
#endif
      ;
      virtual ~ProcessMonitor (void);

      virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

      virtual void _dispatch (
          TAO_ServerRequest & req,
          TAO::Portable_Server::Servant_Upcall *servant_upcall);
      
      ::OpenDDS::Monitor::ProcessMonitor *_this (void);
      
      virtual const char* _interface_repository_id (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::OpenDDS::Monitor::GenericReport * retrieve_report (
        const char * name) = 0;

      static void retrieve_report_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void enable_report_collection (
        void) = 0;

      static void enable_report_collection_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void disable_report_collection (
        void) = 0;

      static void disable_report_collection_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void enable_report_publishing (
        void) = 0;

      static void enable_report_publishing_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void diable_report_publishing (
        void) = 0;

      static void diable_report_publishing_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual void set_publishing_period (
        const ::DDS::Duration_t & period) = 0;

      static void set_publishing_period_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:35

      virtual ::DDS::Duration_t get_publishing_period (
        void) = 0;

      static void get_publishing_period_skel (
          TAO_ServerRequest &server_request,
          TAO::Portable_Server::Servant_Upcall *servant_upcall,
          TAO_ServantBase *servant);
    };
  
  
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:65

  } // module OpenDDS::Monitor


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:65

} // module OpenDDS

OPENDDS_END_VERSIONED_NAMESPACE_DECL



#include /**/ "ace/post.h"

#endif /* ifndef */

