// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_TYPELOOKUPC_HXHW00_H_
#define _TAO_IDL_TYPELOOKUPC_HXHW00_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "rtps_export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"
#include /**/ "dds/Versioned_Namespace.h"

#include "dds/DCPS/XTypes/TypeObjectC.h"
#include "dds/DCPS/RTPS/RtpsRpcC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 23
#error This file should be regenerated with TAO_IDL
#endif

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



OPENDDS_END_VERSIONED_NAMESPACE_DECL



OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace OpenDDS
{
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

  namespace XTypes
  {
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const CORBA::Long DDS_RETCODE_OK = 0;
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const CORBA::Long TypeLookup_getTypes_HashId = 25318099;
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    const CORBA::Long TypeLookup_getDependencies_HashId = 95091505;
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct TypeLookup_getTypes_In;

    typedef
      ::TAO_Var_Var_T<
          TypeLookup_getTypes_In
        >
      TypeLookup_getTypes_In_var;

    typedef
      ::TAO_Out_T<
          TypeLookup_getTypes_In
        >
      TypeLookup_getTypes_In_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Rtps_Export TypeLookup_getTypes_In
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TypeLookup_getTypes_In_var _var_type;
      typedef TypeLookup_getTypes_In_out _out_type;
      
      OpenDDS::XTypes::TypeIdentifierSeq type_ids;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct TypeLookup_getTypes_Out;

    typedef
      ::TAO_Var_Var_T<
          TypeLookup_getTypes_Out
        >
      TypeLookup_getTypes_Out_var;

    typedef
      ::TAO_Out_T<
          TypeLookup_getTypes_Out
        >
      TypeLookup_getTypes_Out_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Rtps_Export TypeLookup_getTypes_Out
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TypeLookup_getTypes_Out_var _var_type;
      typedef TypeLookup_getTypes_Out_out _out_type;
      
      OpenDDS::XTypes::TypeIdentifierTypeObjectPairSeq types;
      OpenDDS::XTypes::TypeIdentifierPairSeq complete_to_minimal;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    class TypeLookup_getTypes_Result;

    typedef
      ::TAO_Var_Var_T<
          TypeLookup_getTypes_Result
        >
      TypeLookup_getTypes_Result_var;

    typedef
      ::TAO_Out_T<
          TypeLookup_getTypes_Result
        >
      TypeLookup_getTypes_Result_out;

    class OpenDDS_Rtps_Export TypeLookup_getTypes_Result
    {
    public:
      TypeLookup_getTypes_Result (void);
      TypeLookup_getTypes_Result (const TypeLookup_getTypes_Result &);
      ~TypeLookup_getTypes_Result (void);

      TypeLookup_getTypes_Result &operator= (const TypeLookup_getTypes_Result &);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ch.cpp:98

      

      void _d ( ::CORBA::Long);
      ::CORBA::Long _d (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TypeLookup_getTypes_Result_var _var_type;
      typedef TypeLookup_getTypes_Result_out _out_type;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void result (const OpenDDS::XTypes::TypeLookup_getTypes_Out &);
      const OpenDDS::XTypes::TypeLookup_getTypes_Out &result (void) const;
      OpenDDS::XTypes::TypeLookup_getTypes_Out &result (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ch.cpp:120

      

      void _default (void);
    private:
      ::CORBA::Long disc_;

      union
      {
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::XTypes::TypeLookup_getTypes_Out *result_;
      } u_;

      /// TAO extension - frees any allocated storage.
      void _reset (void);
    };

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

    

#if !defined (_OPENDDS_XTYPES_OCTETSEQ32_CH_)
#define _OPENDDS_XTYPES_OCTETSEQ32_CH_

    class OctetSeq32;
    typedef ::TAO_FixedSeq_Var_T<OctetSeq32> OctetSeq32_var;
    typedef ::TAO_Seq_Out_T<OctetSeq32> OctetSeq32_out;
    

    class OpenDDS_Rtps_Export OctetSeq32
      : public
          ::TAO::bounded_value_sequence< ::CORBA::Octet,32>
    {
    public:
      OctetSeq32 (void);
      OctetSeq32 (
        ::CORBA::ULong length,
        ::CORBA::Octet* buffer,
        ::CORBA::Boolean release = false);
#if defined (ACE_HAS_CPP11)
      OctetSeq32 (const OctetSeq32 &) = default;
      OctetSeq32 (OctetSeq32 &&) = default;
      OctetSeq32& operator= (const OctetSeq32 &) = default;
      OctetSeq32& operator= (OctetSeq32 &&) = default;
#endif /* ACE_HAS_CPP11 */
      virtual ~OctetSeq32 (void);
      
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef OctetSeq32_var _var_type;
      typedef OctetSeq32_out _out_type;
    };

#endif /* end #if !defined */
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct TypeLookup_getTypeDependencies_In;

    typedef
      ::TAO_Var_Var_T<
          TypeLookup_getTypeDependencies_In
        >
      TypeLookup_getTypeDependencies_In_var;

    typedef
      ::TAO_Out_T<
          TypeLookup_getTypeDependencies_In
        >
      TypeLookup_getTypeDependencies_In_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Rtps_Export TypeLookup_getTypeDependencies_In
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TypeLookup_getTypeDependencies_In_var _var_type;
      typedef TypeLookup_getTypeDependencies_In_out _out_type;
      
      OpenDDS::XTypes::TypeIdentifierSeq type_ids;
      OpenDDS::XTypes::OctetSeq32 continuation_point;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct TypeLookup_getTypeDependencies_Out;

    typedef
      ::TAO_Var_Var_T<
          TypeLookup_getTypeDependencies_Out
        >
      TypeLookup_getTypeDependencies_Out_var;

    typedef
      ::TAO_Out_T<
          TypeLookup_getTypeDependencies_Out
        >
      TypeLookup_getTypeDependencies_Out_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Rtps_Export TypeLookup_getTypeDependencies_Out
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TypeLookup_getTypeDependencies_Out_var _var_type;
      typedef TypeLookup_getTypeDependencies_Out_out _out_type;
      
      OpenDDS::XTypes::TypeIdentifierWithSizeSeq dependent_typeids;
      OpenDDS::XTypes::OctetSeq32 continuation_point;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    class TypeLookup_getTypeDependencies_Result;

    typedef
      ::TAO_Var_Var_T<
          TypeLookup_getTypeDependencies_Result
        >
      TypeLookup_getTypeDependencies_Result_var;

    typedef
      ::TAO_Out_T<
          TypeLookup_getTypeDependencies_Result
        >
      TypeLookup_getTypeDependencies_Result_out;

    class OpenDDS_Rtps_Export TypeLookup_getTypeDependencies_Result
    {
    public:
      TypeLookup_getTypeDependencies_Result (void);
      TypeLookup_getTypeDependencies_Result (const TypeLookup_getTypeDependencies_Result &);
      ~TypeLookup_getTypeDependencies_Result (void);

      TypeLookup_getTypeDependencies_Result &operator= (const TypeLookup_getTypeDependencies_Result &);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ch.cpp:98

      

      void _d ( ::CORBA::Long);
      ::CORBA::Long _d (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TypeLookup_getTypeDependencies_Result_var _var_type;
      typedef TypeLookup_getTypeDependencies_Result_out _out_type;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void result (const OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out &);
      const OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out &result (void) const;
      OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out &result (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ch.cpp:120

      

      void _default (void);
    private:
      ::CORBA::Long disc_;

      union
      {
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out *result_;
      } u_;

      /// TAO extension - frees any allocated storage.
      void _reset (void);
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    class TypeLookup_Call;

    typedef
      ::TAO_Var_Var_T<
          TypeLookup_Call
        >
      TypeLookup_Call_var;

    typedef
      ::TAO_Out_T<
          TypeLookup_Call
        >
      TypeLookup_Call_out;

    class OpenDDS_Rtps_Export TypeLookup_Call
    {
    public:
      TypeLookup_Call (void);
      TypeLookup_Call (const TypeLookup_Call &);
      ~TypeLookup_Call (void);

      TypeLookup_Call &operator= (const TypeLookup_Call &);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ch.cpp:98

      

      void _d ( ::CORBA::Long);
      ::CORBA::Long _d (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TypeLookup_Call_var _var_type;
      typedef TypeLookup_Call_out _out_type;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void getTypes (const OpenDDS::XTypes::TypeLookup_getTypes_In &);
      const OpenDDS::XTypes::TypeLookup_getTypes_In &getTypes (void) const;
      OpenDDS::XTypes::TypeLookup_getTypes_In &getTypes (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:681

      

      void getTypeDependencies (const OpenDDS::XTypes::TypeLookup_getTypeDependencies_In &);
      const OpenDDS::XTypes::TypeLookup_getTypeDependencies_In &getTypeDependencies (void) const;
      OpenDDS::XTypes::TypeLookup_getTypeDependencies_In &getTypeDependencies (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ch.cpp:120

      

      void _default (void);
    private:
      ::CORBA::Long disc_;

      union
      {
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::XTypes::TypeLookup_getTypes_In *getTypes_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:520

        
        OpenDDS::XTypes::TypeLookup_getTypeDependencies_In *getTypeDependencies_;
      } u_;

      /// TAO extension - frees any allocated storage.
      void _reset (void);
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct TypeLookup_Request;

    typedef
      ::TAO_Var_Var_T<
          TypeLookup_Request
        >
      TypeLookup_Request_var;

    typedef
      ::TAO_Out_T<
          TypeLookup_Request
        >
      TypeLookup_Request_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Rtps_Export TypeLookup_Request
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TypeLookup_Request_var _var_type;
      typedef TypeLookup_Request_out _out_type;
      
      DDS::RPC::RequestHeader header;
      

      OpenDDS::XTypes::TypeLookup_Call data;
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    class TypeLookup_Return;

    typedef
      ::TAO_Var_Var_T<
          TypeLookup_Return
        >
      TypeLookup_Return_var;

    typedef
      ::TAO_Out_T<
          TypeLookup_Return
        >
      TypeLookup_Return_out;

    class OpenDDS_Rtps_Export TypeLookup_Return
    {
    public:
      TypeLookup_Return (void);
      TypeLookup_Return (const TypeLookup_Return &);
      ~TypeLookup_Return (void);

      TypeLookup_Return &operator= (const TypeLookup_Return &);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ch.cpp:98

      

      void _d ( ::CORBA::Long);
      ::CORBA::Long _d (void) const;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TypeLookup_Return_var _var_type;
      typedef TypeLookup_Return_out _out_type;
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:773

      

      void getType (const OpenDDS::XTypes::TypeLookup_getTypes_Result &);
      const OpenDDS::XTypes::TypeLookup_getTypes_Result &getType (void) const;
      OpenDDS::XTypes::TypeLookup_getTypes_Result &getType (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ch.cpp:773

      

      void getTypeDependencies (const OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result &);
      const OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result &getTypeDependencies (void) const;
      OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result &getTypeDependencies (void);
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ch.cpp:120

      

      void _default (void);
    private:
      ::CORBA::Long disc_;

      union
      {
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:599

        
        OpenDDS::XTypes::TypeLookup_getTypes_Result *getType_;
        // TAO_IDL - Generated from
        // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/private_ch.cpp:599

        
        OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result *getTypeDependencies_;
      } u_;

      /// TAO extension - frees any allocated storage.
      void _reset (void);
    };
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

    

    struct TypeLookup_Reply;

    typedef
      ::TAO_Var_Var_T<
          TypeLookup_Reply
        >
      TypeLookup_Reply_var;

    typedef
      ::TAO_Out_T<
          TypeLookup_Reply
        >
      TypeLookup_Reply_out;

    
    // TAO_IDL - Generated from
    // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

    

    struct OpenDDS_Rtps_Export TypeLookup_Reply
    {
      // TAO_IDL - Generated from
      // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

      
      typedef TypeLookup_Reply_var _var_type;
      typedef TypeLookup_Reply_out _out_type;
      
      DDS::RPC::ReplyHeader header;
      

      OpenDDS::XTypes::TypeLookup_Return _cxx_return;
    };
  
  
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62

  
  } // module OpenDDS::XTypes


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module OpenDDS
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypes_In>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypes_In,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypes_Out>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypes_Out,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypes_Result>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypes_Result,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::OctetSeq32>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::OctetSeq32,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_In>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_In,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::TypeLookup_Call>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_Call,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::TypeLookup_Request>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_Request,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::TypeLookup_Return>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_Return,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::OpenDDS::XTypes::TypeLookup_Reply>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_Reply,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1649



OPENDDS_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "TypeLookupC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

