// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:454

#ifndef _TAO_IDL_TYPELOOKUPS_JH0PP8_H_
#define _TAO_IDL_TYPELOOKUPS_JH0PP8_H_

#include /**/ "ace/pre.h"

#include "TypeLookupC.h"
#include "dds/DCPS/XTypes/TypeObjectS.h"
#include "dds/DCPS/RTPS/RtpsRpcS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"

// Skeleton file generation suppressed with command line option -SS

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypes_In>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypes_In,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypes_Out>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypes_Out,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypes_Result>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypes_Result,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:672

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::OctetSeq32>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::OctetSeq32,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_In>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_In,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::TypeLookup_Call>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_Call,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::TypeLookup_Request>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_Request,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:1042

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::TypeLookup_Return>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_Return,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::OpenDDS::XTypes::TypeLookup_Reply>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::XTypes::TypeLookup_Reply,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




OPENDDS_END_VERSIONED_NAMESPACE_DECL



#include /**/ "ace/post.h"

#endif /* ifndef */

