// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ci.cpp:35

// *************************************************************
// Inline operations for union OpenDDS::XTypes::TypeLookup_getTypes_Result
// *************************************************************
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ci.cpp:143

ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_getTypes_Result::_default ()
{
  this->_reset ();
  this->disc_ = -2147483647;
}

// Accessor to set the discriminant.
ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_getTypes_Result::_d ( ::CORBA::Long discval)
{
  this->disc_ = discval;
}

// Accessor to get the discriminant.
ACE_INLINE
::CORBA::Long
OpenDDS::XTypes::TypeLookup_getTypes_Result::_d (void) const
{
  return this->disc_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_getTypes_Result::result (const OpenDDS::XTypes::TypeLookup_getTypes_Out &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = 0;
  ACE_NEW (
      this->u_.result_,
      OpenDDS::XTypes::TypeLookup_getTypes_Out (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::XTypes::TypeLookup_getTypes_Out &
OpenDDS::XTypes::TypeLookup_getTypes_Result::result (void) const
{
  return *this->u_.result_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::XTypes::TypeLookup_getTypes_Out &
OpenDDS::XTypes::TypeLookup_getTypes_Result::result (void)
{
  return *this->u_.result_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ci.cpp:35

// *************************************************************
// Inline operations for union OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result
// *************************************************************
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ci.cpp:143

ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result::_default ()
{
  this->_reset ();
  this->disc_ = -2147483647;
}

// Accessor to set the discriminant.
ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result::_d ( ::CORBA::Long discval)
{
  this->disc_ = discval;
}

// Accessor to get the discriminant.
ACE_INLINE
::CORBA::Long
OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result::_d (void) const
{
  return this->disc_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result::result (const OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = 0;
  ACE_NEW (
      this->u_.result_,
      OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out &
OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result::result (void) const
{
  return *this->u_.result_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::XTypes::TypeLookup_getTypeDependencies_Out &
OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result::result (void)
{
  return *this->u_.result_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ci.cpp:35

// *************************************************************
// Inline operations for union OpenDDS::XTypes::TypeLookup_Call
// *************************************************************
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ci.cpp:143

ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_Call::_default ()
{
  this->_reset ();
  this->disc_ = -2147483647;
}

// Accessor to set the discriminant.
ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_Call::_d ( ::CORBA::Long discval)
{
  this->disc_ = discval;
}

// Accessor to get the discriminant.
ACE_INLINE
::CORBA::Long
OpenDDS::XTypes::TypeLookup_Call::_d (void) const
{
  return this->disc_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_Call::getTypes (const OpenDDS::XTypes::TypeLookup_getTypes_In &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = 25318099;
  ACE_NEW (
      this->u_.getTypes_,
      OpenDDS::XTypes::TypeLookup_getTypes_In (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::XTypes::TypeLookup_getTypes_In &
OpenDDS::XTypes::TypeLookup_Call::getTypes (void) const
{
  return *this->u_.getTypes_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::XTypes::TypeLookup_getTypes_In &
OpenDDS::XTypes::TypeLookup_Call::getTypes (void)
{
  return *this->u_.getTypes_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1068

/// Accessor to set the member.
ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_Call::getTypeDependencies (const OpenDDS::XTypes::TypeLookup_getTypeDependencies_In &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = 95091505;
  ACE_NEW (
      this->u_.getTypeDependencies_,
      OpenDDS::XTypes::TypeLookup_getTypeDependencies_In (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::XTypes::TypeLookup_getTypeDependencies_In &
OpenDDS::XTypes::TypeLookup_Call::getTypeDependencies (void) const
{
  return *this->u_.getTypeDependencies_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::XTypes::TypeLookup_getTypeDependencies_In &
OpenDDS::XTypes::TypeLookup_Call::getTypeDependencies (void)
{
  return *this->u_.getTypeDependencies_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/union_ci.cpp:35

// *************************************************************
// Inline operations for union OpenDDS::XTypes::TypeLookup_Return
// *************************************************************
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union/discriminant_ci.cpp:143

ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_Return::_default ()
{
  this->_reset ();
  this->disc_ = -2147483647;
}

// Accessor to set the discriminant.
ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_Return::_d ( ::CORBA::Long discval)
{
  this->disc_ = discval;
}

// Accessor to get the discriminant.
ACE_INLINE
::CORBA::Long
OpenDDS::XTypes::TypeLookup_Return::_d (void) const
{
  return this->disc_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1234

// Accessor to set the member.
ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_Return::getType (const OpenDDS::XTypes::TypeLookup_getTypes_Result &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = 25318099;
  ACE_NEW (
      this->u_.getType_,
      OpenDDS::XTypes::TypeLookup_getTypes_Result (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::XTypes::TypeLookup_getTypes_Result &
OpenDDS::XTypes::TypeLookup_Return::getType (void) const
{
  return *this->u_.getType_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::XTypes::TypeLookup_getTypes_Result &
OpenDDS::XTypes::TypeLookup_Return::getType (void)
{
  return *this->u_.getType_;
}
// TAO_IDL - Generated from
// /workspaces/testdds/lib/OpenDDS/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_union_branch/public_ci.cpp:1234

// Accessor to set the member.
ACE_INLINE
void
OpenDDS::XTypes::TypeLookup_Return::getTypeDependencies (const OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result &val)
{
  // Set the discriminant value.
  this->_reset ();
  this->disc_ = 95091505;
  ACE_NEW (
      this->u_.getTypeDependencies_,
      OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result (val)
    );
}

// Readonly get method.
ACE_INLINE
const OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result &
OpenDDS::XTypes::TypeLookup_Return::getTypeDependencies (void) const
{
  return *this->u_.getTypeDependencies_;
}

// Read/write get method.
ACE_INLINE
OpenDDS::XTypes::TypeLookup_getTypeDependencies_Result &
OpenDDS::XTypes::TypeLookup_Return::getTypeDependencies (void)
{
  return *this->u_.getTypeDependencies_;
}


OPENDDS_END_VERSIONED_NAMESPACE_DECL


